"""
Brand context models – the critical context pipeline for real outputs.

BrandContext: stores structured brand information for a workspace.
This data is injected into every CrewAI agent's context so that
generated content reflects the actual business, not generic AI output.

BrandAsset: uploaded files (photos, logos, past content) that agents
can reference when creating content suggestions.

Migration note (2025-05-07):
  If you are running against an existing database, apply the SQL in
  backend/migrations/0001_brand_context_discovery_fields.sql
  before restarting the service.  New tables get all columns automatically.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import DateTime, ForeignKey, String, Text, Integer
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import BaseModel

if TYPE_CHECKING:
    from app.models.workspace import Workspace


class BrandContext(BaseModel):
    __tablename__ = "brand_contexts"

    workspace_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("workspaces.id", ondelete="CASCADE"),
        unique=True,
        nullable=False,
    )

    # ── Core identity (pre-existing) ──────────────────────────────────────
    business_name: Mapped[str] = mapped_column(String(255), nullable=False)
    business_type: Mapped[str] = mapped_column(String(100), nullable=False)
    description: Mapped[str | None] = mapped_column(Text)
    # Widened from String(100) → Text so inferred values (200+ chars) are not truncated
    brand_tone: Mapped[str | None] = mapped_column(Text)
    visual_style: Mapped[str | None] = mapped_column(Text)
    target_audience: Mapped[str | None] = mapped_column(Text)
    location: Mapped[str | None] = mapped_column(String(255))
    languages: Mapped[str] = mapped_column(String(100), default="tr")
    campaign_goals: Mapped[str | None] = mapped_column(Text)
    competitors: Mapped[str | None] = mapped_column(Text)
    # AI-suggested competitors (JSON list of strings) — shown to user as chip suggestions
    suggested_competitors: Mapped[str | None] = mapped_column(Text)
    custom_rules: Mapped[str | None] = mapped_column(Text)
    keywords: Mapped[str | None] = mapped_column(Text)

    # ── Discovery source URLs (added 2025-05-07) ─────────────────────────
    website_url: Mapped[str | None] = mapped_column(Text)
    instagram_handle: Mapped[str | None] = mapped_column(String(100))
    google_business_url: Mapped[str | None] = mapped_column(Text)

    # ── Discovery output — JSON Text columns, parse with json.loads() ──────
    # e.g. '["daily_story","menu_share"]'
    content_pillars: Mapped[str | None] = mapped_column(Text)
    # e.g. '["Rezervasyon Yap","Menüye Bak"]'
    default_ctas: Mapped[str | None] = mapped_column(Text)
    # e.g. '{"price":"approval_required","date":"approval_required"}'
    risk_rules: Mapped[str | None] = mapped_column(Text)
    instagram_top_hashtags: Mapped[str | None] = mapped_column(Text)
    website_summary: Mapped[str | None] = mapped_column(Text)
    instagram_bio: Mapped[str | None] = mapped_column(Text)
    reference_image_urls: Mapped[str | None] = mapped_column(Text)
    competitor_brief: Mapped[str | None] = mapped_column(Text)
    # Weekly seasonal + location trend context (refreshed every 7 days).
    # Injected into Content Strategy Agent for time-relevant content planning.
    trend_brief: Mapped[str | None] = mapped_column(Text)
    # Timestamp of last trend_brief refresh (ISO string stored as text)
    trend_brief_updated_at: Mapped[str | None] = mapped_column(String(50))
    # Social listening signals — brand mentions, hashtag trends, competitor activity
    social_signals: Mapped[str | None] = mapped_column(Text)
    social_signals_updated_at: Mapped[str | None] = mapped_column(String(50))
    # Monthly strategic brief — GPT-4o senior account manager brief for next 30 days
    monthly_brief: Mapped[str | None] = mapped_column(Text)
    monthly_brief_updated_at: Mapped[str | None] = mapped_column(String(50))
    # Brand DNA — weekly GPT-4o synthesis of ALL brand signals → master intelligence layer
    brand_dna: Mapped[str | None] = mapped_column(Text)
    brand_dna_updated_at: Mapped[str | None] = mapped_column(String(50))
    # Sector-specific intelligence calendar — generated by IndustryIntelligenceService
    # JSON: season_phases, current_phase, upcoming_triggers, weekly_rhythms, etc.
    industry_calendar: Mapped[str | None] = mapped_column(Text)
    industry_intelligence_updated_at: Mapped[str | None] = mapped_column(String(50))
    # Gallery analysis cache — JSON map of URL → {tags, description, assetType, usageContext}
    gallery_analysis: Mapped[str | None] = mapped_column(Text)
    # Structured website crawl: menu categories, product/venue photos, brand display name
    website_intelligence: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    # Daily competitor activity digest — refreshed by Market Intelligence Agent
    competitor_pulse: Mapped[str | None] = mapped_column(Text)
    # JSON array: urgent content ideas from today's market scan
    market_opportunity_ideas: Mapped[str | None] = mapped_column(Text)
    # Timestamp of last market intelligence run
    market_intelligence_updated_at: Mapped[str | None] = mapped_column(String(50))

    # ── Extended brand intelligence (added 0012) ──────────────────────────
    # Tripadvisor reviews — JSON list of {text, rating, date, language}
    tripadvisor_reviews: Mapped[str | None] = mapped_column(Text)
    # Hyper-local Instagram posts — JSON list of {caption, hashtags, likes}
    location_posts: Mapped[str | None] = mapped_column(Text)
    # Google Trends data — JSON list of {keyword, interestOverTime, relatedQueries}
    google_trends: Mapped[str | None] = mapped_column(Text)
    # Timestamp of last extended intelligence refresh
    extended_intelligence_updated_at: Mapped[str | None] = mapped_column(String(50))

    # AI-generated visual identity analysis (GPT-4o Vision on reference_image_urls).
    # Describes color palette, mood, lighting, materials, venue aesthetic.
    # Used in agent prompts so content/visual direction stays venue-consistent.
    visual_dna: Mapped[str | None] = mapped_column(Text)
    # JSON array: top Google review excerpts + sentiment signals
    # e.g. [{"text":"deniz çok temiz","stars":5},{"text":"personel güler yüzlü","stars":5}]
    google_review_signals: Mapped[str | None] = mapped_column(Text)
    # Aggregate Google rating (float) and review count (int)
    google_rating: Mapped[str | None] = mapped_column(String(20))
    google_review_count: Mapped[int | None] = mapped_column(Integer)

    # Per-tenant LLM override — NULL = global smart routing
    llm_provider: Mapped[str | None] = mapped_column(String(32))
    llm_model: Mapped[str | None] = mapped_column(String(128))

    # Assigned Creatomate template ID for this brand's video pack
    creatomate_template_id: Mapped[str | None] = mapped_column(String(128))

    # ── Brand Vibe Profile (agency-grade reference DNA) ───────────────────
    # JSONB dict with: palette, typography, motion, grading, audio,
    # composition, caption_voice, content_pillars_visual, anti_patterns,
    # reference_frames (R2-mirrored URLs).
    # Extracted from external reference IG accounts via /api/extract-vibe.
    brand_vibe_profile: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    brand_vibe_profile_updated_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True,
    )

    # ── Brand Theme (derived design tokens — migration 0017) ─────────────
    # Produced by brand_theme_service.derive_brand_theme().
    # Waterfall: vibe_profile → visual_dna → manual_colors → sector_default.
    brand_theme: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    brand_theme_updated_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True,
    )

    # Official brand logo URL (from website or Instagram profile)
    logo_url: Mapped[str | None] = mapped_column(String(512))

    # Creatomate brand template config — per-tenant video pack styling
    brand_primary_color: Mapped[str | None] = mapped_column(String(16))
    brand_accent_color: Mapped[str | None] = mapped_column(String(16))
    brand_font_family: Mapped[str | None] = mapped_column(String(64))
    brand_overlay_opacity: Mapped[float | None] = mapped_column()

    # Pinterest visual inspiration — top pins from sector-specific queries
    visual_inspiration: Mapped[str | None] = mapped_column(Text)
    visual_inspiration_updated_at: Mapped[str | None] = mapped_column(String(50))

    # ── Discovery metadata ────────────────────────────────────────────────
    discovery_confidence: Mapped[int | None] = mapped_column(Integer)
    last_brand_analysis_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    brand_constitution_confirmed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    # ── CEO Intelligence cache (Sprint C) ─────────────────────────────────
    # Persisted so recommendations survive server restarts.
    # JSON array of RecommendedTask objects; refreshed by the daily scheduler.
    cached_recommendations: Mapped[str | None] = mapped_column(Text)
    recommendations_cached_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    # ── Mission orchestration fields (Task 2 / migration 0010) ────────────
    # Tracks the industry calendar phase name seen on the previous scheduler run.
    # The phase-change detector (Task 3) compares the current phase against this
    # value; a mismatch fires a new MissionProposal with type="seasonal".
    last_known_phase: Mapped[str | None] = mapped_column(String(200))

    # The mission currently executing for this workspace (NULL when idle).
    # Set to missions.id when a mission transitions to "in_flight",
    # cleared when it reaches "completed", "rejected", or "cancelled".
    # Stored as String (not UUID FK) to avoid a circular import between
    # brand_context.py and mission.py at module load time.
    active_mission_id: Mapped[str | None] = mapped_column(String(36))

    workspace: Mapped[Workspace] = relationship(back_populates="brand_context")
    assets: Mapped[list[BrandAsset]] = relationship(
        back_populates="brand_context", cascade="all, delete-orphan"
    )


class BrandAsset(BaseModel):
    __tablename__ = "brand_assets"

    brand_context_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("brand_contexts.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    asset_type: Mapped[str] = mapped_column(String(50), nullable=False)
    file_name: Mapped[str] = mapped_column(String(255), nullable=False)
    file_path: Mapped[str] = mapped_column(String(512), nullable=False)
    content_type: Mapped[str | None] = mapped_column(String(100))
    file_size_bytes: Mapped[int | None] = mapped_column(Integer)
    description: Mapped[str | None] = mapped_column(Text)
    tags: Mapped[str | None] = mapped_column(Text)

    brand_context: Mapped[BrandContext] = relationship(back_populates="assets")
