'use client';
/**
 * BRAND RULES SCREEN — Operator review for auto-promoted learning patterns.
 *
 * Shows pending BrandRule proposals (status=under_review) generated by the
 * weekly learning promoter. Operator approves or rejects each one.
 * Approved rules are immediately applied to BrandContext.
 *
 * Rule types:
 *   cta               — "Rezervasyon Yap" kullanıldı 7+ kez
 *   format_preference — "reel" %85 onay oranıyla tercih ediliyor
 *   format_avoidance  — "carousel" %22 onay oranı — kaçın
 *   hook_pattern      — "question" hook tipi kanıtlandı
 */
import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { useTheme } from '../theme-context';
import { useMobileStore } from '../mobile-store';
import { useWorkspaceStore } from '@/stores/workspace-store';
import { useAuthStore } from '../auth-store';
import { apiClient } from '@/lib/api-client';
import type { BrandRuleItem } from '@/types';

// ── Helpers ───────────────────────────────────────────────────────────────────

const RULE_TYPE_META: Record<string, { label: string; icon: string; color: string }> = {
  cta:               { label: 'Onaylı CTA',         icon: '💬', color: '#10B981' },
  format_preference: { label: 'Tercih Edilen Format', icon: '✦',  color: '#A78BFA' },
  format_avoidance:  { label: 'Kaçınılacak Format',  icon: '⚠',  color: '#F59E0B' },
  hook_pattern:      { label: 'Kanıtlı Hook Tipi',   icon: '◎',  color: '#60A5FA' },
  content_pillar:    { label: 'İçerik Sütunu',        icon: '⬡',  color: '#F472B6' },
};

function ConfidenceBar({ value, color }: { value: number; color: string }) {
  const pct = Math.round(value * 100);
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
      <div style={{ flex: 1, height: 4, borderRadius: 2, background: 'rgba(160,160,180,0.15)', overflow: 'hidden' }}>
        <div style={{ height: '100%', width: `${pct}%`, borderRadius: 2, background: color, transition: 'width 0.4s ease' }} />
      </div>
      <span style={{ fontSize: 10, color, fontWeight: 700, flexShrink: 0 }}>{pct}%</span>
    </div>
  );
}

function RuleCard({ rule, onApprove, onReject, isApproving, isRejecting }: {
  rule: BrandRuleItem;
  onApprove: () => void;
  onReject: () => void;
  isApproving: boolean;
  isRejecting: boolean;
}) {
  const { t } = useTheme();
  const meta = RULE_TYPE_META[rule.rule_type] ?? { label: rule.rule_type, icon: '◇', color: t.accent };
  const isPending = isApproving || isRejecting;

  return (
    <div style={{
      borderRadius: 18, overflow: 'hidden',
      background: t.isDark ? 'rgba(255,255,255,0.04)' : '#fff',
      border: `0.5px solid ${t.separator}`,
      boxShadow: t.isDark ? 'none' : '0 2px 12px rgba(0,0,0,0.06)',
    }}>
      <div style={{ height: 3, background: `linear-gradient(90deg, ${meta.color}cc, ${meta.color}22)` }} />
      <div style={{ padding: '14px 16px' }}>
        {/* Header */}
        <div style={{ display: 'flex', alignItems: 'flex-start', gap: 10, marginBottom: 10 }}>
          <div style={{ width: 36, height: 36, borderRadius: 10,
            background: `${meta.color}12`, border: `0.5px solid ${meta.color}28`,
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            fontSize: 17, flexShrink: 0 }}>
            {meta.icon}
          </div>
          <div style={{ flex: 1, minWidth: 0 }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 5, marginBottom: 3 }}>
              <span style={{ fontSize: 9, padding: '2px 7px', borderRadius: 20,
                background: `${meta.color}14`, color: meta.color,
                fontWeight: 700, letterSpacing: '0.04em', textTransform: 'uppercase' }}>
                {meta.label}
              </span>
            </div>
            <div style={{ fontSize: 15, fontWeight: 700, color: t.textPrimary,
              lineHeight: 1.2, letterSpacing: '-0.01em',
              overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
              {rule.rule_key}
            </div>
          </div>
        </div>

        {/* Evidence */}
        {rule.evidence_summary && (
          <div style={{ fontSize: 12, color: t.textTertiary, lineHeight: 1.55, marginBottom: 10 }}>
            {rule.evidence_summary}
          </div>
        )}

        {/* Confidence bar + stats */}
        <div style={{ marginBottom: 12 }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 5 }}>
            <span style={{ fontSize: 10, color: t.textMuted, fontWeight: 600 }}>Güven Skoru</span>
            {rule.approval_rate != null && (
              <span style={{ fontSize: 10, color: t.textMuted }}>
                Onay oranı: %{Math.round(rule.approval_rate * 100)}
              </span>
            )}
          </div>
          <ConfidenceBar value={rule.confidence} color={meta.color} />
          <div style={{ fontSize: 10, color: t.textMuted, marginTop: 4 }}>
            {rule.confirmation_count} kez gözlemlendi · {rule.source}
          </div>
        </div>

        {/* Apply note */}
        {rule.rule_type === 'cta' && (
          <div style={{ fontSize: 11, color: t.live, marginBottom: 10 }}>
            ✓ Onaylanırsa default_ctas listesine eklenir
          </div>
        )}
        {rule.rule_type === 'format_preference' && (
          <div style={{ fontSize: 11, color: t.live, marginBottom: 10 }}>
            ✓ Onaylanırsa content_pillars listesine eklenir
          </div>
        )}
        {rule.rule_type === 'format_avoidance' && (
          <div style={{ fontSize: 11, color: t.warning, marginBottom: 10 }}>
            ⚠ Onaylanırsa risk_rules'a eklenir — ajan bu formatı kullanmaktan kaçınır
          </div>
        )}
        {rule.rule_type === 'hook_pattern' && (
          <div style={{ fontSize: 11, color: t.info, marginBottom: 10 }}>
            ✓ Onaylanırsa custom_rules'a not olarak eklenir
          </div>
        )}

        {/* Approve / Reject */}
        <div style={{ display: 'flex', gap: 8 }}>
          <button
            onClick={onApprove}
            disabled={isPending}
            style={{
              flex: 1, padding: '11px', borderRadius: 13, cursor: isPending ? 'default' : 'pointer',
              background: isPending
                ? (t.isDark ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.05)')
                : `linear-gradient(135deg, ${meta.color}cc, ${meta.color}88)`,
              border: 'none', color: isApproving ? t.textMuted : '#fff',
              fontSize: 13, fontWeight: 700,
              display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 5,
              boxShadow: isPending ? 'none' : `0 2px 12px ${meta.color}40`,
              opacity: isPending ? 0.7 : 1,
            }}>
            {isApproving ? (
              <><div style={{ width: 11, height: 11, borderRadius: '50%',
                border: `2px solid ${t.separator}`, borderTop: `2px solid ${meta.color}`,
                animation: 'spinSlow 0.8s linear infinite' }} />Uygulanıyor...</>
            ) : '✓ Onayla & Uygula'}
          </button>
          <button
            onClick={onReject}
            disabled={isPending}
            style={{
              flex: 1, padding: '11px', borderRadius: 13, cursor: isPending ? 'default' : 'pointer',
              background: t.isDark ? 'rgba(255,255,255,0.04)' : 'rgba(0,0,0,0.04)',
              border: `0.5px solid ${t.separator}`, color: t.textTertiary,
              fontSize: 13, fontWeight: 500, opacity: isPending ? 0.5 : 1,
            }}>
            ✕ Reddet
          </button>
        </div>
      </div>
    </div>
  );
}

// ── Active rules section ──────────────────────────────────────────────────────

function ActiveRuleRow({ rule }: { rule: BrandRuleItem }) {
  const { t } = useTheme();
  const meta = RULE_TYPE_META[rule.rule_type] ?? { label: rule.rule_type, icon: '◇', color: t.accent };
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '11px 0',
      borderBottom: `0.5px solid ${t.separator}` }}>
      <div style={{ width: 28, height: 28, borderRadius: 8, flexShrink: 0,
        background: `${meta.color}12`, display: 'flex', alignItems: 'center',
        justifyContent: 'center', fontSize: 14 }}>
        {meta.icon}
      </div>
      <div style={{ flex: 1, minWidth: 0 }}>
        <div style={{ fontSize: 13, fontWeight: 600, color: t.textSecondary,
          overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
          {rule.rule_key}
        </div>
        <div style={{ fontSize: 10, color: t.textMuted, marginTop: 1 }}>
          {meta.label}
        </div>
      </div>
      <span style={{ fontSize: 10, padding: '2px 8px', borderRadius: 20,
        background: 'rgba(16,185,129,0.10)', color: '#10B981', fontWeight: 700 }}>
        Aktif
      </span>
    </div>
  );
}

// ── Main screen ───────────────────────────────────────────────────────────────

export function BrandRulesScreen() {
  const { t } = useTheme();
  const { goBack } = useMobileStore();
  const { tenantId } = useWorkspaceStore();
  const { user } = useAuthStore();
  const queryClient = useQueryClient();
  const [scanMsg, setScanMsg] = useState<string | null>(null);

  const wsId = tenantId;

  const { data: pendingRules = [], isLoading } = useQuery({
    queryKey: ['brand-rules-pending', wsId],
    queryFn: () => apiClient.getPendingBrandRules(wsId),
    staleTime: 30_000,
    enabled: Boolean(wsId),
  });

  const { data: activeRules = [] } = useQuery({
    queryKey: ['brand-rules-active', wsId],
    queryFn: () => apiClient.listBrandRules(wsId, 'active'),
    staleTime: 60_000,
    enabled: Boolean(wsId),
  });

  const scanMutation = useMutation({
    mutationFn: () => apiClient.scanBrandRules(wsId),
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ['brand-rules-pending', wsId] });
      setScanMsg(data.message);
      setTimeout(() => setScanMsg(null), 4000);
    },
    onError: (err: Error) => setScanMsg(err.message?.slice(0, 100) ?? 'Tarama başarısız'),
  });

  const approveMutation = useMutation({
    mutationFn: (ruleId: string) =>
      apiClient.approveBrandRule(wsId, ruleId, user?.displayName ?? 'operator'),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['brand-rules-pending', wsId] });
      queryClient.invalidateQueries({ queryKey: ['brand-rules-active', wsId] });
    },
  });

  const rejectMutation = useMutation({
    mutationFn: (ruleId: string) => apiClient.rejectBrandRule(wsId, ruleId),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['brand-rules-pending', wsId] }),
  });

  return (
    <div style={{ minHeight: '100dvh', background: t.bg, paddingBottom: 88 }}>
      {/* Header */}
      <div style={{
        padding: 'calc(env(safe-area-inset-top,0px) + 14px) 22px 0',
        display: 'flex', alignItems: 'center', gap: 12,
      }}>
        <button onClick={goBack} style={{ ...t.backBtn, cursor: 'pointer',
          width: 34, height: 34, borderRadius: '50%', display: 'flex',
          alignItems: 'center', justifyContent: 'center', fontSize: 18 }}>
          ←
        </button>
        <div style={{ flex: 1 }}>
          <div style={{ fontSize: 22, fontWeight: 800, color: t.textPrimary,
            letterSpacing: '-0.03em', lineHeight: 1.1 }}>
            Marka Kuralları
          </div>
          <div style={{ fontSize: 12, color: t.textMuted, marginTop: 1 }}>
            Öğrenme verisinden otomatik öneriler
          </div>
        </div>
        <button
          onClick={() => { setScanMsg(null); scanMutation.mutate(); }}
          disabled={scanMutation.isPending}
          style={{
            padding: '8px 14px', borderRadius: 30,
            cursor: scanMutation.isPending ? 'default' : 'pointer',
            background: scanMutation.isPending
              ? (t.isDark ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.06)')
              : t.accentDim,
            border: `0.5px solid ${t.accentBorder}`,
            color: scanMutation.isPending ? t.textMuted : t.accent,
            fontSize: 12, fontWeight: 700,
            display: 'flex', alignItems: 'center', gap: 5,
          }}>
          {scanMutation.isPending ? (
            <><div style={{ width: 10, height: 10, borderRadius: '50%',
              border: `2px solid ${t.separator}`, borderTop: `2px solid ${t.accent}`,
              animation: 'spinSlow 0.8s linear infinite' }} />Tarıyor...</>
          ) : '⟳ Tara'}
        </button>
      </div>

      {scanMsg && (
        <div style={{ margin: '10px 22px 0', padding: '9px 13px', borderRadius: 10,
          background: t.accentDim, border: `0.5px solid ${t.accentBorder}`,
          fontSize: 12, color: t.accent }}>
          {scanMsg}
        </div>
      )}

      <div style={{ padding: '24px 22px 0' }}>

        {/* Loading */}
        {isLoading && (
          <div style={{ textAlign: 'center', paddingTop: 50 }}>
            <div style={{ width: 28, height: 28, borderRadius: '50%',
              border: `3px solid ${t.separator}`, borderTop: `3px solid ${t.accent}`,
              animation: 'spinSlow 1s linear infinite', margin: '0 auto 12px' }} />
            <div style={{ fontSize: 13, color: t.textMuted }}>Kurallar yükleniyor...</div>
          </div>
        )}

        {/* Pending rules */}
        {pendingRules.length > 0 && (
          <div style={{ marginBottom: 28 }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 14 }}>
              <div style={{ width: 6, height: 6, borderRadius: '50%', background: t.warning,
                animation: 'liveGlow 2s infinite', boxShadow: `0 0 8px ${t.warning}` }} />
              <span style={{ fontSize: 11, fontWeight: 700, color: t.labelColor,
                letterSpacing: '0.1em', textTransform: 'uppercase' }}>Onay Bekliyor</span>
              <span style={{ fontSize: 11, padding: '1px 7px', borderRadius: 20,
                background: 'rgba(245,158,11,0.12)', color: t.warning, fontWeight: 700 }}>
                {pendingRules.length}
              </span>
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
              {pendingRules.map(rule => (
                <RuleCard
                  key={rule.id}
                  rule={rule}
                  onApprove={() => approveMutation.mutate(rule.id)}
                  onReject={() => rejectMutation.mutate(rule.id)}
                  isApproving={approveMutation.isPending && approveMutation.variables === rule.id}
                  isRejecting={rejectMutation.isPending && rejectMutation.variables === rule.id}
                />
              ))}
            </div>
          </div>
        )}

        {/* Empty pending */}
        {!isLoading && pendingRules.length === 0 && (
          <div style={{ textAlign: 'center', paddingTop: 30, paddingBottom: 20 }}>
            <div style={{ fontSize: 32, marginBottom: 10 }}>✓</div>
            <div style={{ fontSize: 15, fontWeight: 700, color: t.textSecondary, marginBottom: 6 }}>
              Onay bekleyen kural yok
            </div>
            <div style={{ fontSize: 12, color: t.textMuted, lineHeight: 1.6, maxWidth: 260, margin: '0 auto' }}>
              Haftalık promoter onay geçmişini tarar. Manuel tarama için "Tara" butonuna bas.
            </div>
          </div>
        )}

        {/* Active rules */}
        {activeRules.length > 0 && (
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 10 }}>
              <span style={{ fontSize: 11, fontWeight: 700, color: t.labelColor,
                letterSpacing: '0.1em', textTransform: 'uppercase' }}>Aktif Kurallar</span>
              <span style={{ fontSize: 11, padding: '1px 7px', borderRadius: 20,
                background: 'rgba(16,185,129,0.10)', color: '#10B981', fontWeight: 700 }}>
                {activeRules.length}
              </span>
            </div>
            <div style={{ borderRadius: 16, overflow: 'hidden',
              background: t.isDark ? 'rgba(255,255,255,0.03)' : '#fff',
              border: `0.5px solid ${t.separator}`, padding: '0 14px' }}>
              {activeRules.map((rule, i) => (
                <div key={rule.id} style={{ borderBottom: i < activeRules.length - 1 ? undefined : 'none' }}>
                  <ActiveRuleRow rule={rule} />
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
