namespace Nexus.Contracts.Dtos;

public record TenantMediaAssetDto(
    Guid Id,
    Guid? OfficeId,
    string AssetType,
    string Url,
    string StorageKey,
    string DisplayName,
    string Description,
    string Tags,
    string UsageContext,
    bool IsApproved,
    int Priority,
    DateTime CreatedAt,
    DateTime UpdatedAt);

public record UpsertTenantMediaAssetRequest(
    Guid? OfficeId,
    string AssetType,
    string Url,
    string StorageKey = "",
    string DisplayName = "",
    string Description = "",
    string Tags = "[]",
    string UsageContext = "",
    bool IsApproved = true,
    int Priority = 0);

public record OfficeBrandProfileDto(
    Guid Id,
    Guid OfficeId,
    string DisplayName,
    string Location,
    string LogoUrl,
    string BrandColors,
    string AccentColors,
    string Contact,
    string WebsiteUrl,
    string ReservationUrl,
    string SocialTemplateStyle,
    string DefaultCta,
    string Configuration,
    DateTime CreatedAt,
    DateTime UpdatedAt);

public record UpsertOfficeBrandProfileRequest(
    Guid OfficeId,
    string DisplayName = "",
    string Location = "",
    string LogoUrl = "",
    string BrandColors = "",
    string AccentColors = "",
    string Contact = "",
    string WebsiteUrl = "",
    string ReservationUrl = "",
    string SocialTemplateStyle = "",
    string DefaultCta = "",
    string Configuration = "{}");

public record CanvaTemplateAssignmentDto(
    Guid Id,
    Guid? OfficeId,
    string CanvaTemplateId,
    string Name,
    string ContentKinds,
    string UseCases,
    string TemplateFamilyId,
    string AllowedIntents,
    string AllowedChannels,
    string RequiredAssetIntents,
    string RiskTier,
    string Status,
    bool ManualApprovalRequired,
    DateTime? LastReviewedAt,
    Guid? LastReviewedBy,
    string AspectRatio,
    string DatasetContract,
    bool Enabled,
    int Priority,
    int BrandFitScore,
    string Notes,
    DateTime CreatedAt,
    DateTime UpdatedAt);

public record UpsertCanvaTemplateAssignmentRequest(
    Guid? OfficeId,
    string CanvaTemplateId,
    string Name,
    string ContentKinds = "[]",
    string UseCases = "[]",
    string TemplateFamilyId = "",
    string AllowedIntents = "[]",
    string AllowedChannels = "[]",
    string RequiredAssetIntents = "[]",
    string RiskTier = "low",
    string Status = "draft",
    bool ManualApprovalRequired = false,
    string AspectRatio = "freeform",
    string DatasetContract = "{}",
    bool Enabled = true,
    int Priority = 0,
    int BrandFitScore = 0,
    string Notes = "");
