/**
 * Agency announcement template catalog — 200 layouts across 20 families.
 *
 * Inspired by luxury invite/editorial patterns (Pinterest, Dribbble, Linearity,
 * PostNitro beach-club guidance): photo-first, typographic hierarchy, restrained overlays.
 * Poster/lineup families inspired by Coachella, Lollapalooza, Tomorrowland, Art Deco gala,
 * club-night flyers and e-commerce promo banners.
 */

import type {
  AnnouncementTemplateDefinition,
  AnnouncementTemplateId,
  LayoutFamily,
  TemplateCollection,
  TemplateLayoutSpec,
} from './announcement-template-types';

const BASE_SPEC: TemplateLayoutSpec = {
  family: 'luxury_bottom',
  gradientStart: 0.55,
  gradientPeak: 0.55,
  gradientEnd: 0.82,
  textBleed: false,
  photoFirst: false,
  textZone: 'bottom_center',
  align: 'center',
  heroScale: 1.0,
  heroWeight: 'bold',
  heroUppercase: true,
  heroTracking: 0.06,
  showVenueBadge: true,
  accentLine: 'none',
  accentLineWidth: 0.18,
  showBrand: true,
  showTagline: true,
  taglineItalic: true,
  dateBadge: 'none',
  stripOnly: false,
  stripOpacity: 0.38,
  bandMode: 'none',
  bandHeight: 0.22,
  frame: 'none',
  diagonal: false,
  frostedCard: false,
  frostedY: 0.62,
  sideBar: 'none',
  vignetteDeep: false,
  colorBlock: 'none',
  colorBlockOpacity: 0.9,
  colorBlockSize: 0.4,
  heroStyle: 'display',
  duotoneWash: 'none',
  duotoneOpacity: 0.45,
  cornerStamp: 'none',
  magazineDate: 'none',
  neonGlow: false,
  sideVerticalLabel: 'none',
  posterMode: 'none',
  ornamentDivider: 'none',
  posterHeader: 'none',
  posterFooter: 'none',
  cornerOrnament: false,
};

type FamilyMeta = {
  family: LayoutFamily;
  collection: TemplateCollection;
  icon: string;
  nameTr: string;
  nameEn: string;
  descTr: string;
  descEn: string;
  inspiration: string;
  useCases: AnnouncementTemplateDefinition['useCases'];
  previewHint: AnnouncementTemplateDefinition['previewHint'];
  formats?: AnnouncementTemplateDefinition['formats'];
  base: Partial<TemplateLayoutSpec>;
  variants: Array<{ suffix: string; suffixTr: string; patch: Partial<TemplateLayoutSpec>; tags?: string[] }>;
};

const FAMILY_CATALOG: FamilyMeta[] = [
  {
    family: 'luxury_bottom',
    collection: 'Luxury',
    icon: '✦',
    nameTr: 'Lüks Alt',
    nameEn: 'Luxury Bottom',
    descTr: 'Alt gradient, ortalanmış hero — beach club & resort davetiye stili.',
    descEn: 'Bottom fade, centered hero — resort invitation style.',
    inspiration: 'PostNitro luxury beach invite · sand/ivory typography stacks',
    useCases: ['event', 'announcement'],
    previewHint: 'bottom_center',
    base: {
      family: 'luxury_bottom',
      textZone: 'bottom_center',
      align: 'center',
      gradientStart: 0.55,
      showVenueBadge: true,
      accentLine: 'above',
    },
    variants: [
      { suffix: 'Classic', suffixTr: 'Klasik', patch: {} },
      { suffix: 'Wide Rule', suffixTr: 'Geniş Çizgi', patch: { accentLineWidth: 0.28 } },
      { suffix: 'Fine Rule', suffixTr: 'İnce Çizgi', patch: { accentLineWidth: 0.10 } },
      { suffix: 'No Rule', suffixTr: 'Çizgisiz', patch: { accentLine: 'none' } },
      { suffix: 'Twin Rules', suffixTr: 'Çift Çizgi', patch: { accentLine: 'both', accentLineWidth: 0.14 } },
      { suffix: 'Soft Fade', suffixTr: 'Yumuşak Fade', patch: { gradientStart: 0.62, gradientEnd: 0.72 } },
      { suffix: 'Deep Fade', suffixTr: 'Derin Fade', patch: { gradientStart: 0.48, gradientEnd: 0.88 } },
      { suffix: 'Wide Type', suffixTr: 'Geniş Tracking', patch: { heroTracking: 0.14 } },
      { suffix: 'Light Hero', suffixTr: 'İnce Hero', patch: { heroWeight: '300', heroUppercase: false } },
      { suffix: 'No Badge', suffixTr: 'Rozetsiz', patch: { showVenueBadge: false } },
    ],
  },
  {
    family: 'editorial_left',
    collection: 'Editorial',
    icon: '◧',
    nameTr: 'Editoryal Sol',
    nameEn: 'Editorial Left',
    descTr: 'Sol hizalı tipografi — bar booking & magazine story.',
    descEn: 'Left-aligned editorial stack.',
    inspiration: 'Linearity bar booking · left rule + cocktail focus',
    useCases: ['announcement', 'campaign'],
    previewHint: 'bottom_left',
    base: {
      family: 'editorial_left',
      textZone: 'bottom_left',
      align: 'start',
      gradientStart: 0.50,
      sideBar: 'left',
      accentLine: 'none',
      showVenueBadge: false,
    },
    variants: [
      { suffix: 'Classic', suffixTr: 'Klasik', patch: {} },
      { suffix: 'Bold Bar', suffixTr: 'Kalın Bar', patch: { sideBar: 'left' } },
      { suffix: 'Right Bar', suffixTr: 'Sağ Bar', patch: { sideBar: 'right', textZone: 'bottom_right', align: 'end' } },
      { suffix: 'Compact', suffixTr: 'Kompakt', patch: { heroScale: 0.88, gradientStart: 0.58 } },
      { suffix: 'Tall', suffixTr: 'Uzun Stack', patch: { heroScale: 1.12 } },
      { suffix: 'No Brand', suffixTr: 'Markasız', patch: { showBrand: false } },
      { suffix: 'Tagline Off', suffixTr: 'Tagsız', patch: { showTagline: false } },
      { suffix: 'Light', suffixTr: 'Light Weight', patch: { heroWeight: '300' } },
      { suffix: 'Deep', suffixTr: 'Derin', patch: { gradientStart: 0.42, gradientEnd: 0.86 } },
      { suffix: 'Uppercase', suffixTr: 'Büyük Harf', patch: { heroTracking: 0.10 } },
    ],
  },
  {
    family: 'campaign_badge',
    collection: 'Campaign',
    icon: '◉',
    nameTr: 'Kampanya Rozeti',
    nameEn: 'Campaign Badge',
    descTr: 'Üstte tarih rozeti — launch & promo hierarchy.',
    descEn: 'Top date pill with bottom hero.',
    inspiration: 'BrandCrowd event story · date-first campaign frames',
    useCases: ['campaign', 'event'],
    previewHint: 'top_badge',
    base: {
      family: 'campaign_badge',
      dateBadge: 'top_pill',
      gradientStart: 0.52,
      showVenueBadge: false,
      accentLine: 'none',
    },
    variants: [
      { suffix: 'Center Pill', suffixTr: 'Orta Pill', patch: { dateBadge: 'top_pill' } },
      { suffix: 'Corner Tag', suffixTr: 'Köşe Tag', patch: { dateBadge: 'top_left_pill' } },
      { suffix: 'Above Hero', suffixTr: 'Hero Üstü', patch: { dateBadge: 'above_hero' } },
      { suffix: 'Bold Hero', suffixTr: 'Kalın Hero', patch: { heroScale: 1.15 } },
      { suffix: 'Minimal Pill', suffixTr: 'Minimal Pill', patch: { heroScale: 0.92, gradientStart: 0.58 } },
      { suffix: 'Night', suffixTr: 'Gece', patch: { gradientEnd: 0.90, vignetteDeep: true }, tags: ['nightlife'] },
      { suffix: 'Soft', suffixTr: 'Yumuşak', patch: { gradientEnd: 0.70 } },
      { suffix: 'Wide Pill', suffixTr: 'Geniş Pill', patch: {} },
      { suffix: 'No Brand', suffixTr: 'Markasız', patch: { showBrand: false } },
      { suffix: 'Impact', suffixTr: 'Impact', patch: { heroWeight: 'bold', heroTracking: 0.12 } },
    ],
  },
  {
    family: 'minimal_whisper',
    collection: 'Minimal',
    icon: '—',
    nameTr: 'Minimal',
    nameEn: 'Minimal Whisper',
    descTr: 'İnce alt şerit — sade duyuru & soft luxury.',
    descEn: 'Thin bottom strip, quiet typography.',
    inspiration: 'Luxury restraint · cut decorative filler (PostNitro)',
    useCases: ['announcement'],
    previewHint: 'minimal',
    base: {
      family: 'minimal_whisper',
      stripOnly: true,
      gradientStart: 0.74,
      showVenueBadge: false,
      accentLine: 'none',
      showBrand: false,
      showTagline: false,
      heroWeight: '500',
      heroUppercase: false,
    },
    variants: [
      { suffix: 'Whisper', suffixTr: 'Fısıltı', patch: { stripOpacity: 0.32 } },
      { suffix: 'Soft', suffixTr: 'Soft', patch: { stripOpacity: 0.26 } },
      { suffix: 'Solid', suffixTr: 'Solid', patch: { stripOpacity: 0.48 } },
      { suffix: 'Left', suffixTr: 'Sol', patch: { textZone: 'bottom_left', align: 'start' } },
      { suffix: 'Center', suffixTr: 'Orta', patch: { textZone: 'bottom_center', align: 'center' } },
      { suffix: 'With Brand', suffixTr: 'Markalı', patch: { showBrand: true } },
      { suffix: 'With Tag', suffixTr: 'Tagline', patch: { showTagline: true, taglineItalic: true } },
      { suffix: 'Light', suffixTr: 'Light', patch: { heroWeight: '300' } },
      { suffix: 'Tight', suffixTr: 'Dar Şerit', patch: { gradientStart: 0.80 } },
      { suffix: 'Wide', suffixTr: 'Geniş Şerit', patch: { gradientStart: 0.68 } },
    ],
  },
  {
    family: 'impact_vignette',
    collection: 'Impact',
    icon: '◎',
    nameTr: 'Impact',
    nameEn: 'Impact Vignette',
    descTr: 'Derin vignette, kalın ortalanmış tipografi.',
    descEn: 'Deep vignette, bold centered type.',
    inspiration: 'DJ night promos · high contrast event posters',
    useCases: ['event', 'campaign'],
    previewHint: 'vignette',
    formats: ['story', 'post'],
    base: {
      family: 'impact_vignette',
      vignetteDeep: true,
      gradientStart: 0.42,
      gradientEnd: 0.88,
      textZone: 'center',
      align: 'center',
      heroScale: 1.18,
      accentLine: 'below',
      showVenueBadge: false,
    },
    variants: [
      { suffix: 'Center', suffixTr: 'Merkez', patch: {} },
      { suffix: 'Lower', suffixTr: 'Alt', patch: { textZone: 'bottom_center', gradientStart: 0.50 } },
      { suffix: 'Upper', suffixTr: 'Üst', patch: { textZone: 'top_center', gradientStart: 0.20 } },
      { suffix: 'Rule Off', suffixTr: 'Çizgisiz', patch: { accentLine: 'none' } },
      { suffix: 'Double Rule', suffixTr: 'Çift', patch: { accentLine: 'both' } },
      { suffix: 'Heavy', suffixTr: 'Ağır', patch: { gradientEnd: 0.92 } },
      { suffix: 'Light', suffixTr: 'Hafif', patch: { gradientEnd: 0.75, heroScale: 1.05 } },
      { suffix: 'Wide', suffixTr: 'Geniş', patch: { heroTracking: 0.14 } },
      { suffix: 'Sans Feel', suffixTr: 'Modern', patch: { heroUppercase: true, heroWeight: 'bold' } },
      { suffix: 'Serif Feel', suffixTr: 'Serif', patch: { heroWeight: '600', heroUppercase: false } },
    ],
  },
  {
    family: 'offer_band',
    collection: 'Campaign',
    icon: '▬',
    nameTr: 'Kampanya Bandı',
    nameEn: 'Offer Band',
    descTr: 'Accent renk bandı — promo & fırsat duyuruları.',
    descEn: 'Accent colour band for offers.',
    inspiration: 'Neon pool party promos · bold bottom CTA bands',
    useCases: ['campaign'],
    previewHint: 'accent_band',
    base: {
      family: 'offer_band',
      bandMode: 'accent_bottom',
      bandHeight: 0.22,
      gradientStart: 0.56,
      showVenueBadge: false,
      accentLine: 'none',
    },
    variants: [
      { suffix: 'Solid', suffixTr: 'Düz Band', patch: { bandMode: 'accent_bottom' } },
      { suffix: 'Rounded', suffixTr: 'Yuvarlak', patch: { bandMode: 'accent_bottom_rounded' } },
      { suffix: 'Primary', suffixTr: 'Primary Band', patch: { bandMode: 'primary_bottom' } },
      { suffix: 'Slim', suffixTr: 'İnce Band', patch: { bandHeight: 0.16 } },
      { suffix: 'Wide', suffixTr: 'Geniş Band', patch: { bandHeight: 0.28 } },
      { suffix: 'No Tagline', suffixTr: 'Kısa', patch: { showTagline: false } },
      { suffix: 'Bold Type', suffixTr: 'Kalın', patch: { heroScale: 1.08 } },
      { suffix: 'Soft Top', suffixTr: 'Soft Üst', patch: { gradientStart: 0.62 } },
      { suffix: 'Compact', suffixTr: 'Kompakt', patch: { heroScale: 0.9, bandHeight: 0.18 } },
      { suffix: 'Launch', suffixTr: 'Lansman', patch: { heroUppercase: true, heroTracking: 0.10 } },
    ],
  },
  {
    family: 'diagonal_split',
    collection: 'Modern',
    icon: '◢',
    nameTr: 'Diagonal',
    nameEn: 'Diagonal Split',
    descTr: 'Çapraz gradient — editorial Pinterest layout.',
    descEn: 'Diagonal fade split.',
    inspiration: 'Pinterest editorial splits · asymmetric luxury posts',
    useCases: ['announcement', 'campaign', 'event'],
    previewHint: 'diagonal',
    base: {
      family: 'diagonal_split',
      diagonal: true,
      gradientStart: 0.45,
      textZone: 'bottom_left',
      align: 'start',
      sideBar: 'left',
      showVenueBadge: false,
    },
    variants: [
      { suffix: 'Left Stack', suffixTr: 'Sol Stack', patch: {} },
      { suffix: 'Right Stack', suffixTr: 'Sağ Stack', patch: { textZone: 'bottom_right', align: 'end', sideBar: 'right' } },
      { suffix: 'Center', suffixTr: 'Orta', patch: { textZone: 'bottom_center', align: 'center', sideBar: 'none' } },
      { suffix: 'Steep', suffixTr: 'Dik', patch: { gradientStart: 0.38 } },
      { suffix: 'Gentle', suffixTr: 'Hafif', patch: { gradientStart: 0.52, gradientEnd: 0.72 } },
      { suffix: 'Bold', suffixTr: 'Kalın', patch: { heroScale: 1.1 } },
      { suffix: 'Minimal', suffixTr: 'Minimal', patch: { showBrand: false, showTagline: false } },
      { suffix: 'With Rule', suffixTr: 'Çizgili', patch: { accentLine: 'above', accentLineWidth: 0.22 } },
      { suffix: 'Night', suffixTr: 'Gece', patch: { gradientEnd: 0.90 }, tags: ['nightlife'] },
      { suffix: 'Day', suffixTr: 'Gündüz', patch: { gradientEnd: 0.68 } },
    ],
  },
  {
    family: 'frosted_panel',
    collection: 'Modern',
    icon: '▢',
    nameTr: 'Frosted Panel',
    nameEn: 'Frosted Panel',
    descTr: 'Cam panel kart — Dribbble glassmorphism.',
    descEn: 'Frosted glass card overlay.',
    inspiration: 'Dribbble glass UI · frosted story cards',
    useCases: ['announcement', 'event'],
    previewHint: 'frosted',
    base: {
      family: 'frosted_panel',
      frostedCard: true,
      frostedY: 0.58,
      gradientStart: 0.50,
      textZone: 'bottom_center',
      align: 'center',
      showVenueBadge: false,
      accentLine: 'none',
    },
    variants: [
      { suffix: 'Bottom Card', suffixTr: 'Alt Kart', patch: { frostedY: 0.62 } },
      { suffix: 'Mid Card', suffixTr: 'Orta Kart', patch: { frostedY: 0.48, textZone: 'center' } },
      { suffix: 'Wide Card', suffixTr: 'Geniş', patch: { frostedY: 0.55, heroScale: 1.05 } },
      { suffix: 'Compact', suffixTr: 'Kompakt', patch: { frostedY: 0.68, heroScale: 0.9 } },
      { suffix: 'Left Card', suffixTr: 'Sol Kart', patch: { textZone: 'bottom_left', align: 'start', frostedY: 0.60 } },
      { suffix: 'Soft', suffixTr: 'Soft', patch: { gradientStart: 0.58 } },
      { suffix: 'Dark', suffixTr: 'Koyu', patch: { gradientEnd: 0.88 } },
      { suffix: 'No Brand', suffixTr: 'Markasız', patch: { showBrand: false } },
      { suffix: 'Italic Tag', suffixTr: 'Italic Tag', patch: { showTagline: true, taglineItalic: true } },
      { suffix: 'Launch', suffixTr: 'Lansman', patch: { dateBadge: 'above_hero' } },
    ],
  },
  {
    family: 'frame_classic',
    collection: 'Luxury',
    icon: '◻',
    nameTr: 'Çerçeve',
    nameEn: 'Classic Frame',
    descTr: 'İnce çerçeve — davetiye & gala estetiği.',
    descEn: 'Inset frame, invitation aesthetic.',
    inspiration: 'Formal invitation frames · gala / wedding editorial',
    useCases: ['event', 'announcement'],
    previewHint: 'frame',
    base: {
      family: 'frame_classic',
      frame: 'inset',
      gradientStart: 0.52,
      textZone: 'bottom_center',
      align: 'center',
      accentLine: 'both',
      accentLineWidth: 0.12,
    },
    variants: [
      { suffix: 'Single', suffixTr: 'Tek', patch: { frame: 'inset' } },
      { suffix: 'Double', suffixTr: 'Çift', patch: { frame: 'double' } },
      { suffix: 'No Frame', suffixTr: 'Framesiz', patch: { frame: 'none' } },
      { suffix: 'Tight', suffixTr: 'Dar', patch: { heroScale: 0.92 } },
      { suffix: 'Grand', suffixTr: 'Grand', patch: { heroScale: 1.08, heroTracking: 0.10 } },
      { suffix: 'Venue', suffixTr: 'Venue', patch: { showVenueBadge: true } },
      { suffix: 'Minimal Frame', suffixTr: 'Minimal', patch: { accentLine: 'none', showTagline: false } },
      { suffix: 'Soft', suffixTr: 'Soft Fade', patch: { gradientEnd: 0.72 } },
      { suffix: 'Deep', suffixTr: 'Deep', patch: { gradientEnd: 0.86 } },
      { suffix: 'Left', suffixTr: 'Sol', patch: { textZone: 'bottom_left', align: 'start' } },
    ],
  },
  {
    family: 'top_masthead',
    collection: 'Hospitality',
    icon: '▴',
    nameTr: 'Üst Masthead',
    nameEn: 'Top Masthead',
    descTr: 'Üst gradient & hero — poster / program duyurusu.',
    descEn: 'Top-weighted masthead layout.',
    inspiration: 'Event poster mastheads · program schedule stories',
    useCases: ['event', 'announcement'],
    previewHint: 'top_center',
    base: {
      family: 'top_masthead',
      textZone: 'top_center',
      align: 'center',
      gradientStart: 0.08,
      gradientPeak: 0.35,
      gradientEnd: 0.55,
      showBrand: true,
      accentLine: 'below',
      dateBadge: 'none',
    },
    variants: [
      { suffix: 'Classic', suffixTr: 'Klasik', patch: {} },
      { suffix: 'With Pill', suffixTr: 'Tarih Pill', patch: { dateBadge: 'top_pill' } },
      { suffix: 'Left', suffixTr: 'Sol', patch: { textZone: 'top_center', align: 'start' } },
      { suffix: 'Bold', suffixTr: 'Kalın', patch: { heroScale: 1.12 } },
      { suffix: 'Light', suffixTr: 'Light', patch: { heroWeight: '300', heroUppercase: false } },
      { suffix: 'Bottom Brand', suffixTr: 'Alt Marka', patch: { showBrand: true } },
      { suffix: 'No Tag', suffixTr: 'Kısa', patch: { showTagline: false } },
      { suffix: 'Deep Top', suffixTr: 'Koyu Üst', patch: { gradientEnd: 0.65 } },
      { suffix: 'Soft Top', suffixTr: 'Soft Üst', patch: { gradientEnd: 0.45 } },
      { suffix: 'Night', suffixTr: 'Gece', patch: { vignetteDeep: true, gradientEnd: 0.70 }, tags: ['nightlife'] },
    ],
  },
  {
    family: 'color_split',
    collection: 'Modern',
    icon: '◫',
    nameTr: 'Renk Blok',
    nameEn: 'Color Split',
    descTr: 'Solid marka paneli + fotoğraf split — Dribbble/Orshot story layout.',
    descEn: 'Solid brand panel split with photo — high-contrast story frame.',
    inspiration: 'Sup Growth split-screen · Envato multi-panel event stories · Dribbble color blocks',
    useCases: ['event', 'campaign', 'announcement'],
    previewHint: 'color_split',
    base: {
      family: 'color_split',
      colorBlock: 'bottom_panel',
      colorBlockOpacity: 0.93,
      colorBlockSize: 0.42,
      gradientStart: 0.48,
      textZone: 'bottom_center',
      align: 'center',
      showVenueBadge: false,
      accentLine: 'none',
    },
    variants: [
      { suffix: 'Bottom Panel', suffixTr: 'Alt Panel', patch: { colorBlock: 'bottom_panel', colorBlockSize: 0.42 } },
      { suffix: 'Left Panel', suffixTr: 'Sol Panel', patch: { colorBlock: 'left_panel', colorBlockSize: 0.44, textZone: 'bottom_left', align: 'start', sideBar: 'left' } },
      { suffix: 'Right Panel', suffixTr: 'Sağ Panel', patch: { colorBlock: 'right_panel', colorBlockSize: 0.44, textZone: 'bottom_right', align: 'end', sideBar: 'right' } },
      { suffix: 'Top Bar', suffixTr: 'Üst Bar', patch: { colorBlock: 'top_bar', colorBlockSize: 0.22, textZone: 'top_center', gradientStart: 0.18 } },
      { suffix: 'Wide Panel', suffixTr: 'Geniş Panel', patch: { colorBlockSize: 0.50 } },
      { suffix: 'Slim Panel', suffixTr: 'İnce Panel', patch: { colorBlockSize: 0.34, heroScale: 0.92 } },
      { suffix: 'Primary Fill', suffixTr: 'Primary', patch: { colorBlock: 'bottom_panel' }, tags: ['primary'] },
      { suffix: 'Soft Opacity', suffixTr: 'Soft', patch: { colorBlockOpacity: 0.78 } },
      { suffix: 'Bold Type', suffixTr: 'Kalın', patch: { heroScale: 1.12, heroTracking: 0.10 } },
      { suffix: 'Launch', suffixTr: 'Lansman', patch: { dateBadge: 'top_pill', showBrand: true } },
    ],
  },
  {
    family: 'script_luxe',
    collection: 'Luxury',
    icon: '✒',
    nameTr: 'Script Lüks',
    nameEn: 'Script Luxe',
    descTr: 'Davetiye script hero + serif detay — Art Deco / gala estetiği.',
    descEn: 'Invitation script headline with serif details.',
    inspiration: 'Design.com Art Deco celebration · wedding editorial · CAC Champagne pairing',
    useCases: ['event', 'announcement'],
    previewHint: 'script',
    base: {
      family: 'script_luxe',
      heroStyle: 'script',
      heroUppercase: false,
      heroWeight: '600',
      heroScale: 1.08,
      heroTracking: 0.02,
      accentLine: 'both',
      accentLineWidth: 0.14,
      frame: 'inset',
      showTagline: true,
      taglineItalic: true,
      gradientStart: 0.52,
    },
    variants: [
      { suffix: 'Invitation', suffixTr: 'Davetiye', patch: {} },
      { suffix: 'Grand Opening', suffixTr: 'Açılış', patch: { frame: 'double', heroScale: 1.12 } },
      { suffix: 'Fine Dining', suffixTr: 'Fine Dining', patch: { showVenueBadge: true, accentLine: 'above' } },
      { suffix: 'Outline Hero', suffixTr: 'Outline', patch: { heroStyle: 'outline' } },
      { suffix: 'Knockout', suffixTr: 'Knockout', patch: { heroStyle: 'knockout', frame: 'none' } },
      { suffix: 'No Frame', suffixTr: 'Framesiz', patch: { frame: 'none', accentLine: 'below' } },
      { suffix: 'Left Stack', suffixTr: 'Sol', patch: { textZone: 'bottom_left', align: 'start' } },
      { suffix: 'Soft Fade', suffixTr: 'Soft', patch: { gradientEnd: 0.72 } },
      { suffix: 'Deep Fade', suffixTr: 'Derin', patch: { gradientEnd: 0.88 } },
      { suffix: 'Minimal', suffixTr: 'Minimal', patch: { showBrand: false, accentLine: 'none' } },
    ],
  },
  {
    family: 'neon_night',
    collection: 'Nightlife',
    icon: '⚡',
    nameTr: 'Neon Gece',
    nameEn: 'Neon Night',
    descTr: 'Duotone wash + neon glow — pool party & club promo.',
    descEn: 'Duotone wash with neon glow — nightlife promos.',
    inspiration: 'VistaPrint Neon-Noir 2026 · pool party PSD · PosterMyWall sunset DJ stories',
    useCases: ['event', 'campaign'],
    previewHint: 'neon',
    formats: ['story', 'post'],
    base: {
      family: 'neon_night',
      duotoneWash: 'accent',
      duotoneOpacity: 0.50,
      neonGlow: true,
      vignetteDeep: true,
      gradientStart: 0.38,
      gradientEnd: 0.92,
      textZone: 'center',
      align: 'center',
      heroScale: 1.14,
      heroUppercase: true,
      heroTracking: 0.12,
      showVenueBadge: false,
      accentLine: 'below',
    },
    variants: [
      { suffix: 'Club Glow', suffixTr: 'Club', patch: {} },
      { suffix: 'Primary Wash', suffixTr: 'Primary Wash', patch: { duotoneWash: 'primary', duotoneOpacity: 0.42 } },
      { suffix: 'Heavy Glow', suffixTr: 'Ağır Glow', patch: { duotoneOpacity: 0.62, neonGlow: true } },
      { suffix: 'Soft Neon', suffixTr: 'Soft Neon', patch: { duotoneOpacity: 0.35, neonGlow: true } },
      { suffix: 'Lower Stack', suffixTr: 'Alt', patch: { textZone: 'bottom_center', gradientStart: 0.50 } },
      { suffix: 'Outline Type', suffixTr: 'Outline', patch: { heroStyle: 'outline', neonGlow: false } },
      { suffix: 'No Glow', suffixTr: 'Glowsuz', patch: { neonGlow: false, duotoneWash: 'accent' } },
      { suffix: 'Wide Type', suffixTr: 'Geniş', patch: { heroTracking: 0.16 } },
      { suffix: 'Compact', suffixTr: 'Kompakt', patch: { heroScale: 0.95 } },
      { suffix: 'Side Label', suffixTr: 'Yan Etiket', patch: { sideVerticalLabel: 'right', textZone: 'bottom_center' } },
    ],
  },
  {
    family: 'magazine_date',
    collection: 'Editorial Type',
    icon: '№',
    nameTr: 'Magazine Tarih',
    nameEn: 'Magazine Date',
    descTr: 'Dev tarih watermark + editoryal stack — fashion poster.',
    descEn: 'Oversized date watermark with editorial stack.',
    inspiration: 'Pinterest summer typography posters · editorial fashion invites · oversized numeral trend',
    useCases: ['event', 'announcement'],
    previewHint: 'magazine',
    base: {
      family: 'magazine_date',
      magazineDate: 'watermark',
      textZone: 'bottom_left',
      align: 'start',
      sideBar: 'left',
      heroScale: 1.02,
      heroUppercase: true,
      gradientStart: 0.46,
      showVenueBadge: false,
    },
    variants: [
      { suffix: 'Watermark', suffixTr: 'Watermark', patch: { magazineDate: 'watermark' } },
      { suffix: 'Stacked Date', suffixTr: 'Stacked', patch: { magazineDate: 'stacked', textZone: 'bottom_left', align: 'start' } },
      { suffix: 'Center Hero', suffixTr: 'Orta Hero', patch: { textZone: 'bottom_center', align: 'center', sideBar: 'none' } },
      { suffix: 'Right Align', suffixTr: 'Sağ', patch: { textZone: 'bottom_right', align: 'end', sideBar: 'right' } },
      { suffix: 'Bold', suffixTr: 'Kalın', patch: { heroScale: 1.12 } },
      { suffix: 'Light', suffixTr: 'Light', patch: { heroWeight: '300', heroUppercase: false } },
      { suffix: 'With Pill', suffixTr: 'Pill', patch: { dateBadge: 'top_left_pill' } },
      { suffix: 'Deep', suffixTr: 'Derin', patch: { gradientEnd: 0.86, vignetteDeep: true } },
      { suffix: 'Minimal', suffixTr: 'Minimal', patch: { showBrand: false, showTagline: false } },
      { suffix: 'Knockout', suffixTr: 'Knockout', patch: { heroStyle: 'knockout' } },
    ],
  },
  {
    family: 'corner_stamp',
    collection: 'Hospitality',
    icon: '◯',
    nameTr: 'Köşe Mühür',
    nameEn: 'Corner Stamp',
    descTr: 'Dairesel tarih mührü + alt hero — davetiye & brunch.',
    descEn: 'Circular date seal with bottom hero stack.',
    inspiration: 'Linearity culinary event badge · brunch stamp · invitation wax seal trend',
    useCases: ['event', 'announcement', 'campaign'],
    previewHint: 'stamp',
    base: {
      family: 'corner_stamp',
      cornerStamp: 'top_right',
      textZone: 'bottom_center',
      align: 'center',
      gradientStart: 0.54,
      showVenueBadge: false,
      accentLine: 'above',
      accentLineWidth: 0.16,
    },
    variants: [
      { suffix: 'Top Right', suffixTr: 'Sağ Üst', patch: { cornerStamp: 'top_right' } },
      { suffix: 'Top Left', suffixTr: 'Sol Üst', patch: { cornerStamp: 'top_left' } },
      { suffix: 'With Pill', suffixTr: 'Ek Pill', patch: { dateBadge: 'top_pill' } },
      { suffix: 'Left Stack', suffixTr: 'Sol Stack', patch: { textZone: 'bottom_left', align: 'start', cornerStamp: 'top_right' } },
      { suffix: 'Script Tag', suffixTr: 'Script Tag', patch: { taglineItalic: true, heroStyle: 'script', heroUppercase: false } },
      { suffix: 'Bold', suffixTr: 'Kalın', patch: { heroScale: 1.10 } },
      { suffix: 'Soft', suffixTr: 'Soft', patch: { gradientEnd: 0.72 } },
      { suffix: 'Deep', suffixTr: 'Derin', patch: { gradientEnd: 0.86 } },
      { suffix: 'No Rule', suffixTr: 'Çizgisiz', patch: { accentLine: 'none' } },
      { suffix: 'Brunch', suffixTr: 'Brunch', patch: { showTagline: true, taglineItalic: true, cornerStamp: 'top_left' } },
    ],
  },
  {
    family: 'concert_lineup',
    collection: 'Lineup',
    icon: '🎤',
    nameTr: 'Konser Line-Up',
    nameEn: 'Concert Lineup',
    descTr: 'Konser/festival afiş — headliner büyük, support küçük, tiered stack.',
    descEn: 'Concert poster — headliner top, tiered artist stack, venue footer.',
    inspiration: 'Coachella/Primavera poster hierarchy · bold headliner + diminishing support tiers',
    useCases: ['event'],
    previewHint: 'lineup',
    formats: ['story', 'post'],
    base: {
      family: 'concert_lineup',
      posterMode: 'lineup_tiered',
      ornamentDivider: 'thin_rule',
      posterHeader: 'accent_bar',
      posterFooter: 'solid_bar',
      textZone: 'center',
      align: 'center',
      heroScale: 1.2,
      heroUppercase: true,
      heroTracking: 0.10,
      gradientStart: 0.30,
      gradientEnd: 0.92,
      vignetteDeep: true,
      showVenueBadge: false,
      showBrand: true,
      showTagline: false,
      accentLine: 'none',
    },
    variants: [
      { suffix: 'Tiered Classic', suffixTr: 'Tier Klasik', patch: { posterMode: 'lineup_tiered' } },
      { suffix: 'Stack', suffixTr: 'Stack', patch: { posterMode: 'lineup_stack' } },
      { suffix: 'Diamond Divider', suffixTr: 'Elmas Çizgi', patch: { ornamentDivider: 'diamond' } },
      { suffix: 'Star Row', suffixTr: 'Yıldız Sıra', patch: { ornamentDivider: 'star_row' } },
      { suffix: 'Outline Bar', suffixTr: 'Outline Bar', patch: { posterHeader: 'outline_bar' } },
      { suffix: 'No Header', suffixTr: 'Başlıksız', patch: { posterHeader: 'none' } },
      { suffix: 'Pill Footer', suffixTr: 'Pill Alt', patch: { posterFooter: 'pill_row' } },
      { suffix: 'Neon', suffixTr: 'Neon', patch: { neonGlow: true, duotoneWash: 'accent', duotoneOpacity: 0.35 }, tags: ['nightlife'] },
      { suffix: 'Knockout Hero', suffixTr: 'Knockout', patch: { heroStyle: 'knockout' } },
      { suffix: 'Art Deco', suffixTr: 'Art Deco', patch: { ornamentDivider: 'art_deco', cornerOrnament: true, frame: 'inset' } },
    ],
  },
  {
    family: 'festival_poster',
    collection: 'Poster',
    icon: '🎪',
    nameTr: 'Festival Afiş',
    nameEn: 'Festival Poster',
    descTr: 'Çok gün festival grid — tarih/sahne/sanatçı matrisi.',
    descEn: 'Multi-day festival grid — date/stage/artist matrix poster.',
    inspiration: 'Lollapalooza/Tomorrowland day-grid posters · bold condensed headliners',
    useCases: ['event'],
    previewHint: 'festival',
    formats: ['story', 'post', 'square'],
    base: {
      family: 'festival_poster',
      posterMode: 'festival_grid',
      ornamentDivider: 'double_rule',
      posterHeader: 'accent_bar',
      posterFooter: 'solid_bar',
      textZone: 'center',
      align: 'center',
      heroScale: 1.15,
      heroUppercase: true,
      heroTracking: 0.08,
      gradientStart: 0.25,
      gradientEnd: 0.90,
      vignetteDeep: true,
      showVenueBadge: false,
      showBrand: true,
      accentLine: 'none',
    },
    variants: [
      { suffix: 'Grid Classic', suffixTr: 'Grid Klasik', patch: {} },
      { suffix: 'Neon Grid', suffixTr: 'Neon Grid', patch: { neonGlow: true, duotoneWash: 'accent', duotoneOpacity: 0.40 }, tags: ['nightlife'] },
      { suffix: 'Diamond', suffixTr: 'Elmas', patch: { ornamentDivider: 'diamond' } },
      { suffix: 'Art Deco', suffixTr: 'Art Deco', patch: { ornamentDivider: 'art_deco', cornerOrnament: true, frame: 'double' } },
      { suffix: 'Outline Hero', suffixTr: 'Outline', patch: { heroStyle: 'outline' } },
      { suffix: 'Knockout', suffixTr: 'Knockout', patch: { heroStyle: 'knockout' } },
      { suffix: 'No Footer', suffixTr: 'Altsız', patch: { posterFooter: 'none' } },
      { suffix: 'Pill Footer', suffixTr: 'Pill Alt', patch: { posterFooter: 'pill_row' } },
      { suffix: 'Soft Gradient', suffixTr: 'Soft', patch: { gradientEnd: 0.78 } },
      { suffix: 'Deep Night', suffixTr: 'Derin Gece', patch: { gradientEnd: 0.94, vignetteDeep: true }, tags: ['nightlife'] },
    ],
  },
  {
    family: 'gala_invite',
    collection: 'Luxury',
    icon: '🥂',
    nameTr: 'Gala Davetiye',
    nameEn: 'Gala Invitation',
    descTr: 'Art Deco köşe süsleme, script hero, çift çerçeve — premium davetiye.',
    descEn: 'Art Deco ornaments, script hero, double frame — premium gala invite.',
    inspiration: 'Design.com Art Deco celebration · Gatsby party invitations · gold foil overlays',
    useCases: ['event', 'announcement'],
    previewHint: 'gala',
    base: {
      family: 'gala_invite',
      posterMode: 'gala_centered',
      ornamentDivider: 'art_deco',
      cornerOrnament: true,
      frame: 'double',
      heroStyle: 'script',
      heroUppercase: false,
      heroScale: 1.10,
      heroTracking: 0.02,
      gradientStart: 0.45,
      gradientEnd: 0.85,
      accentLine: 'both',
      accentLineWidth: 0.14,
      showTagline: true,
      taglineItalic: true,
      showBrand: true,
    },
    variants: [
      { suffix: 'Gold Classic', suffixTr: 'Gold Klasik', patch: {} },
      { suffix: 'Display Hero', suffixTr: 'Display Hero', patch: { heroStyle: 'display', heroUppercase: true, heroTracking: 0.08 } },
      { suffix: 'Single Frame', suffixTr: 'Tek Çerçeve', patch: { frame: 'inset' } },
      { suffix: 'No Frame', suffixTr: 'Çerçevesiz', patch: { frame: 'none', cornerOrnament: false } },
      { suffix: 'Diamond Divider', suffixTr: 'Elmas Çizgi', patch: { ornamentDivider: 'diamond' } },
      { suffix: 'Star Row', suffixTr: 'Yıldız Sıra', patch: { ornamentDivider: 'star_row' } },
      { suffix: 'Deep Night', suffixTr: 'Gece', patch: { vignetteDeep: true, gradientEnd: 0.90 }, tags: ['nightlife'] },
      { suffix: 'Soft', suffixTr: 'Soft', patch: { gradientEnd: 0.72 } },
      { suffix: 'Knockout Bar', suffixTr: 'Knockout Bar', patch: { posterHeader: 'knockout_bar', heroStyle: 'display' } },
      { suffix: 'Minimal', suffixTr: 'Minimal', patch: { cornerOrnament: false, ornamentDivider: 'thin_rule', frame: 'inset' } },
    ],
  },
  {
    family: 'dj_night',
    collection: 'Nightlife',
    icon: '🎧',
    nameTr: 'DJ Night',
    nameEn: 'DJ Night',
    descTr: 'DJ set posteri — duotone wash, neon glow, lineup stack.',
    descEn: 'DJ set poster — duotone wash, neon glow hero, lineup stack.',
    inspiration: 'Pool party PSD · club night flyers · neon-noir type treatment',
    useCases: ['event', 'campaign'],
    previewHint: 'dj_set',
    formats: ['story', 'post'],
    base: {
      family: 'dj_night',
      posterMode: 'dj_set',
      neonGlow: true,
      duotoneWash: 'accent',
      duotoneOpacity: 0.45,
      vignetteDeep: true,
      gradientStart: 0.32,
      gradientEnd: 0.92,
      textZone: 'center',
      align: 'center',
      heroScale: 1.22,
      heroUppercase: true,
      heroTracking: 0.14,
      ornamentDivider: 'thin_rule',
      posterFooter: 'transparent_bar',
      showVenueBadge: false,
      showBrand: true,
      accentLine: 'below',
    },
    variants: [
      { suffix: 'Neon Classic', suffixTr: 'Neon Klasik', patch: {} },
      { suffix: 'Primary Wash', suffixTr: 'Primary Wash', patch: { duotoneWash: 'primary', duotoneOpacity: 0.40 } },
      { suffix: 'Heavy Glow', suffixTr: 'Ağır Glow', patch: { duotoneOpacity: 0.58 } },
      { suffix: 'Outline Hero', suffixTr: 'Outline', patch: { heroStyle: 'outline', neonGlow: false } },
      { suffix: 'Knockout', suffixTr: 'Knockout', patch: { heroStyle: 'knockout', neonGlow: false } },
      { suffix: 'Star Divider', suffixTr: 'Yıldız', patch: { ornamentDivider: 'star_row' } },
      { suffix: 'Pill Footer', suffixTr: 'Pill Alt', patch: { posterFooter: 'pill_row' } },
      { suffix: 'Solid Footer', suffixTr: 'Solid Alt', patch: { posterFooter: 'solid_bar' } },
      { suffix: 'Lineup Stack', suffixTr: 'Lineup', patch: { posterMode: 'lineup_stack' } },
      { suffix: 'Compact', suffixTr: 'Kompakt', patch: { heroScale: 1.05, gradientStart: 0.42 } },
    ],
  },
  {
    family: 'promo_banner',
    collection: 'Campaign',
    icon: '📢',
    nameTr: 'Promo Afiş',
    nameEn: 'Promo Banner',
    descTr: 'Split panel promo — büyük teklif/indirim + detaylar.',
    descEn: 'Split panel promo — bold offer headline + detail footer.',
    inspiration: 'Flash sale banners · e-commerce promo stories · countdown posters',
    useCases: ['campaign', 'announcement'],
    previewHint: 'promo',
    base: {
      family: 'promo_banner',
      posterMode: 'promo_split',
      colorBlock: 'bottom_panel',
      colorBlockOpacity: 0.9,
      colorBlockSize: 0.42,
      posterFooter: 'pill_row',
      textZone: 'center',
      align: 'center',
      heroScale: 1.12,
      heroUppercase: true,
      heroTracking: 0.06,
      gradientStart: 0.48,
      gradientEnd: 0.84,
      showVenueBadge: false,
      showBrand: false,
      accentLine: 'above',
      ornamentDivider: 'double_rule',
      duotoneWash: 'primary',
      duotoneOpacity: 0.22,
    },
    variants: [
      { suffix: 'Bottom Panel', suffixTr: 'Alt Panel', patch: {} },
      { suffix: 'Left Panel', suffixTr: 'Sol Panel', patch: { colorBlock: 'left_panel', colorBlockSize: 0.42, textZone: 'bottom_left', align: 'start' } },
      { suffix: 'Knockout Hero', suffixTr: 'Knockout', patch: { heroStyle: 'knockout' } },
      { suffix: 'Outline Hero', suffixTr: 'Outline', patch: { heroStyle: 'outline' } },
      { suffix: 'Neon', suffixTr: 'Neon', patch: { neonGlow: true, duotoneWash: 'accent', duotoneOpacity: 0.30 }, tags: ['nightlife'] },
      { suffix: 'Wide Panel', suffixTr: 'Geniş Panel', patch: { colorBlockSize: 0.48 } },
      { suffix: 'Pill Footer', suffixTr: 'Pill Alt', patch: { posterFooter: 'pill_row' } },
      { suffix: 'Art Deco', suffixTr: 'Art Deco', patch: { ornamentDivider: 'art_deco', cornerOrnament: true } },
      { suffix: 'Double Rule', suffixTr: 'Çift Çizgi', patch: { ornamentDivider: 'double_rule' } },
      { suffix: 'Minimal', suffixTr: 'Minimal', patch: { colorBlock: 'none', posterFooter: 'transparent_bar' } },
    ],
  },
  // ── Bold Caption ─────────────────────────────────────────────────────────────
  // Ref: "VACATION IS CALLING", "GET YOUR TAN" — huge flush-edge display type,
  // photo fully dominant, text bleeds to frame. Condensed display font (Anton).
  {
    family: 'bold_caption',
    collection: 'Bold Impact',
    icon: '⚡',
    nameTr: 'Bold Caption',
    nameEn: 'Bold Caption',
    descTr: 'Büyük kalın display yazı, fotoğraf baskın, metin çerçeve kenarına kadar uzanıyor.',
    descEn: 'Large flush bold display type, photo dominant, text bleeds to edge.',
    inspiration: 'GET YOUR TAN · VACATION IS CALLING · Pinterest bold type posters',
    useCases: ['event', 'campaign', 'announcement'],
    previewHint: 'bold_flush',
    base: {
      family: 'bold_caption',
      textBleed: true,
      photoFirst: true,
      heroScale: 1.45,
      heroWeight: 'bold',
      heroUppercase: true,
      heroTracking: 0.04,
      textZone: 'top_center',
      align: 'start',
      gradientStart: 0.0,
      gradientPeak: 0.0,
      gradientEnd: 0.22,
      vignetteDeep: false,
      showVenueBadge: false,
      showBrand: false,
      showTagline: true,
      taglineItalic: false,
      accentLine: 'none',
      dateBadge: 'none',
      posterFooter: 'solid_bar',
    },
    variants: [
      { suffix: 'Top Left', suffixTr: 'Sol Üst', patch: { align: 'start', textZone: 'top_center' } },
      { suffix: 'Top Right', suffixTr: 'Sağ Üst', patch: { align: 'end', textZone: 'top_center' } },
      { suffix: 'Top Center', suffixTr: 'Orta Üst', patch: { align: 'center', textZone: 'top_center', heroScale: 1.55, heroTracking: 0.02 } },
      { suffix: 'Yellow', suffixTr: 'Sarı Vurgu', patch: { accentLine: 'below', heroScale: 1.5 } },
      { suffix: 'With Date', suffixTr: 'Tarihli', patch: { dateBadge: 'above_hero', heroScale: 1.3 } },
      { suffix: 'Outline', suffixTr: 'Outline', patch: { heroStyle: 'outline', heroScale: 1.6 } },
      { suffix: 'Vignette', suffixTr: 'Vinyet', patch: { vignetteDeep: true, photoFirst: false, gradientEnd: 0.35 } },
      { suffix: 'Knockout', suffixTr: 'Knockout', patch: { heroStyle: 'knockout', heroScale: 1.35 } },
      { suffix: 'Bottom', suffixTr: 'Alt', patch: { textZone: 'bottom_center', align: 'center', heroScale: 1.5, gradientStart: 0.48, gradientEnd: 0.88 } },
      { suffix: 'Brand Bar', suffixTr: 'Marka Bar', patch: { showBrand: true, posterHeader: 'outline_bar' } },
    ],
  },

  // ── Script Caption ────────────────────────────────────────────────────────────
  // Ref: "This and a really good playlist" — elegant cursive floating over a clean
  // photo, whisper minimal, no heavy overlay. The photo is the story.
  {
    family: 'script_caption',
    collection: 'Script',
    icon: '✦',
    nameTr: 'Script Caption',
    nameEn: 'Script Caption',
    descTr: 'Zarif el yazısı metin, temiz fotoğraf üzerinde yüzer, minimal overlay.',
    descEn: 'Elegant cursive text floating over a clean photo, minimal treatment.',
    inspiration: '"This and a really good playlist" · lifestyle whisper captions · Bodrum summer mood',
    useCases: ['event', 'announcement'],
    previewHint: 'script_centered',
    base: {
      family: 'script_caption',
      textBleed: false,
      photoFirst: true,
      heroStyle: 'script',
      heroScale: 1.4,
      heroWeight: '300',
      heroUppercase: false,
      heroTracking: 0.02,
      textZone: 'center',
      align: 'center',
      gradientStart: 0.35,
      gradientPeak: 0.35,
      gradientEnd: 0.60,
      vignetteDeep: false,
      showVenueBadge: false,
      showBrand: false,
      showTagline: false,
      accentLine: 'none',
      dateBadge: 'none',
      posterFooter: 'none',
      stripOnly: false,
    },
    variants: [
      { suffix: 'Center', suffixTr: 'Orta', patch: {} },
      { suffix: 'Lower Third', suffixTr: 'Alt Üçte Bir', patch: { textZone: 'bottom_center', gradientStart: 0.52, gradientEnd: 0.78 } },
      { suffix: 'Upper', suffixTr: 'Üst', patch: { textZone: 'top_center', gradientStart: 0.0, gradientEnd: 0.28 } },
      { suffix: 'With Tagline', suffixTr: 'Alt Metin', patch: { showTagline: true, heroScale: 1.2 } },
      { suffix: 'With Date', suffixTr: 'Tarihli', patch: { showTagline: true, dateBadge: 'above_hero', heroScale: 1.15 } },
      { suffix: 'Vignette', suffixTr: 'Vinyet', patch: { vignetteDeep: true } },
      { suffix: 'Dark Mood', suffixTr: 'Karanlık', patch: { duotoneWash: 'primary', duotoneOpacity: 0.22 } },
      { suffix: 'Warm Tint', suffixTr: 'Sıcak Tint', patch: { duotoneWash: 'accent', duotoneOpacity: 0.14 } },
      { suffix: 'Minimal White', suffixTr: 'Minimal Beyaz', patch: { photoFirst: true, vignetteDeep: false, gradientStart: 0.98 } },
      { suffix: 'With Brand', suffixTr: 'Markalı', patch: { showBrand: true } },
    ],
  },

  // ── Flush Type ────────────────────────────────────────────────────────────────
  // Ref: "Wanna know?" diagonal split, "Aurelle Body GET YOUR TAN" top-right —
  // solid color panel + flush bold type on panel side, photo on the other.
  {
    family: 'flush_type',
    collection: 'Flush Panel',
    icon: '▌',
    nameTr: 'Flush Panel',
    nameEn: 'Flush Type',
    descTr: 'Renk blok + büyük yazı panelde, fotoğraf karşı tarafta. Güçlü editorial kontrast.',
    descEn: 'Color panel + large flush type on panel, photo on opposite side. Bold editorial contrast.',
    inspiration: '"Wanna know?" diagonal · "GET YOUR TAN" editorial · Dribbble color-block type',
    useCases: ['campaign', 'announcement', 'event'],
    previewHint: 'flush_panel',
    base: {
      family: 'flush_type',
      textBleed: true,
      photoFirst: false,
      heroScale: 1.5,
      heroWeight: 'bold',
      heroUppercase: true,
      heroTracking: 0.03,
      textZone: 'bottom_right',
      align: 'end',
      colorBlock: 'right_panel',
      colorBlockOpacity: 0.95,
      colorBlockSize: 0.44,
      gradientStart: 0.6,
      gradientPeak: 0.6,
      gradientEnd: 0.85,
      vignetteDeep: false,
      showVenueBadge: false,
      showBrand: true,
      showTagline: true,
      taglineItalic: false,
      accentLine: 'none',
      dateBadge: 'none',
      posterFooter: 'none',
    },
    variants: [
      { suffix: 'Right Panel', suffixTr: 'Sağ Panel', patch: {} },
      { suffix: 'Left Panel', suffixTr: 'Sol Panel', patch: { colorBlock: 'left_panel', textZone: 'bottom_left', align: 'start' } },
      { suffix: 'Bottom Panel', suffixTr: 'Alt Panel', patch: { colorBlock: 'bottom_panel', textZone: 'bottom_center', align: 'center', heroScale: 1.3, colorBlockSize: 0.38 } },
      { suffix: 'Wide Panel', suffixTr: 'Geniş Panel', patch: { colorBlockSize: 0.52 } },
      { suffix: 'Narrow Panel', suffixTr: 'İnce Panel', patch: { colorBlockSize: 0.36 } },
      { suffix: 'With Date', suffixTr: 'Tarihli', patch: { dateBadge: 'top_pill', heroScale: 1.3 } },
      { suffix: 'Script', suffixTr: 'El Yazısı', patch: { heroStyle: 'script', heroScale: 1.4, heroUppercase: false } },
      { suffix: 'Outline', suffixTr: 'Outline', patch: { heroStyle: 'outline', heroScale: 1.6 } },
      { suffix: 'Diagonal', suffixTr: 'Diagonal', patch: { diagonal: true, colorBlock: 'none', textZone: 'bottom_right', align: 'end' } },
      { suffix: 'Top Strip', suffixTr: 'Üst Şerit', patch: { colorBlock: 'top_bar', textZone: 'top_center', align: 'center', heroScale: 1.2 } },
    ],
  },
];

function mergeSpec(family: FamilyMeta, patch: Partial<TemplateLayoutSpec>): TemplateLayoutSpec {
  return {
    ...BASE_SPEC,
    ...family.base,
    ...patch,
    family: family.family,
  };
}

function buildTemplate(
  family: FamilyMeta,
  index: number,
  variant: FamilyMeta['variants'][number],
): AnnouncementTemplateDefinition {
  const nn = String(index + 1).padStart(2, '0');
  const id = `agency_${family.family}_${nn}` as AnnouncementTemplateId;
  const layout = mergeSpec(family, variant.patch);

  return {
    id,
    family: family.family,
    collection: family.collection,
    name: `${family.nameEn} · ${variant.suffix}`,
    nameTr: `${family.nameTr} · ${variant.suffixTr}`,
    description: `${family.descEn} Variant: ${variant.suffix}.`,
    descriptionTr: `${family.descTr} Varyant: ${variant.suffixTr}.`,
    icon: family.icon,
    useCases: family.useCases,
    formats: family.formats ?? ['story', 'post', 'square'],
    previewHint: family.previewHint,
    tags: ['agency', family.family, family.collection.toLowerCase(), ...(variant.tags ?? [])],
    layout,
    inspiration: family.inspiration,
  };
}

export const AGENCY_TEMPLATE_CATALOG: AnnouncementTemplateDefinition[] = FAMILY_CATALOG.flatMap(
  (family) => family.variants.map((variant, index) => buildTemplate(family, index, variant)),
);

export const LEGACY_TEMPLATE_ALIASES: Record<string, AnnouncementTemplateId> = {
  luxury_bottom: 'agency_luxury_bottom_01',
  editorial_left: 'agency_editorial_left_01',
  campaign_badge: 'agency_campaign_badge_01',
  minimal_whisper: 'agency_minimal_whisper_01',
  impact_vignette: 'agency_impact_vignette_01',
  offer_band: 'agency_offer_band_01',
};

export const TEMPLATE_BY_ID: Map<string, AnnouncementTemplateDefinition> = new Map();

for (const t of AGENCY_TEMPLATE_CATALOG) {
  TEMPLATE_BY_ID.set(t.id, t);
}
for (const [legacyId, canonicalId] of Object.entries(LEGACY_TEMPLATE_ALIASES)) {
  const canonical = TEMPLATE_BY_ID.get(canonicalId);
  if (canonical) {
    TEMPLATE_BY_ID.set(legacyId, { ...canonical, id: legacyId });
  }
}

/** All unique agency templates (200) plus legacy alias entries for lookup */
export const ANNOUNCEMENT_TEMPLATES: AnnouncementTemplateDefinition[] = AGENCY_TEMPLATE_CATALOG;

export const TEMPLATE_FAMILIES: { id: LayoutFamily; labelTr: string; count: number }[] =
  FAMILY_CATALOG.map((f) => ({
    id: f.family,
    labelTr: f.nameTr,
    count: f.variants.length,
  }));

export const TEMPLATE_COLLECTIONS: TemplateCollection[] = [
  'Luxury', 'Editorial', 'Campaign', 'Minimal', 'Impact', 'Hospitality', 'Modern', 'Nightlife', 'Editorial Type', 'Poster', 'Lineup',
];

export function normalizeTemplateId(id: string | undefined | null): AnnouncementTemplateId {
  if (!id) return 'luxury_bottom';
  if (TEMPLATE_BY_ID.has(id)) return id;
  return 'luxury_bottom';
}

export function resolveTemplateLayout(id: string): TemplateLayoutSpec {
  const normalized = normalizeTemplateId(id);
  const def = TEMPLATE_BY_ID.get(normalized);
  if (def) return def.layout;
  const canonicalId = LEGACY_TEMPLATE_ALIASES[normalized];
  if (canonicalId) {
    return TEMPLATE_BY_ID.get(canonicalId)?.layout ?? AGENCY_TEMPLATE_CATALOG[0]!.layout;
  }
  return AGENCY_TEMPLATE_CATALOG[0]!.layout;
}

export function isValidTemplateId(id: string): boolean {
  return TEMPLATE_BY_ID.has(id) || /^agency_[a-z_]+_\d{2}$/.test(id);
}

export function getTemplateDefinition(id: string): AnnouncementTemplateDefinition | undefined {
  return TEMPLATE_BY_ID.get(normalizeTemplateId(id));
}
