/**
 * Remotion template catalog — 100 parametric story layouts (10 families × 10 variants).
 */

import {
  agencyStoryTags,
  getAgencyStoryFamilyUpgrade,
  normalizeAgencyStorySpec,
} from './agency-template-standard';
import type {
  RemotionLayoutFamily,
  RemotionLayoutSpec,
  RemotionTemplateDefinition,
} from './remotion-template-types';

type TemplateIntent =
  | 'daily_moment'
  | 'product_spotlight'
  | 'campaign_offer'
  | 'announcement'
  | 'invitation'
  | 'event'
  | 'social_proof'
  | 'educational';

const BASE_SPEC: RemotionLayoutSpec = {
  family: 'editorial_bottom',
  collection: 'Agency',
  fontPersonality: 'brand',
  headlineTreatment: 'flat',
  heroWeight: 800,
  heroUppercase: true,
  heroTracking: 0.04,
  heroScale: 1.0,
  subtitleItalic: true,
  categoryTracking: 0.12,
  backgroundMode: 'photo_full',
  gradientStart: 0.52,
  gradientEnd: 0.82,
  overlayOpacity: 0.68,
  panelRatio: 0.44,
  kenBurnsOrigin: '40% 60%',
  kenBurnsScale: 1.08,
  vignette: 'soft',
  duotoneWash: 'none',
  duotoneOpacity: 0.35,
  textZone: 'bottom_left',
  align: 'left',
  accentLine: 'left_bar',
  accentLineWidth: 0.04,
  frame: 'none',
  frostedCard: false,
  frostedY: 0.62,
  sideBar: 'none',
  showLocation: true,
  showCtaPill: false,
  categoryVertical: false,
  panelUsesPrimary: true,
  accentOnCategory: true,
  textOnPhoto: true,
  colorPolicy: {
    headline: 'text',
    subtitle: 'text',
    category: 'accent',
    overlay: 'primary',
  },
};

type FamilyMeta = {
  family: RemotionLayoutFamily;
  collection: RemotionLayoutSpec['collection'];
  legacyComposition: RemotionTemplateDefinition['legacyComposition'];
  nameTr: string;
  nameEn: string;
  descTr: string;
  tags: string[];
  bestFor: TemplateIntent[];
  sectors: string[];
  base: Partial<RemotionLayoutSpec>;
  variants: Array<{ suffix: string; suffixTr: string; patch: Partial<RemotionLayoutSpec> }>;
};

const FAMILY_CATALOG: FamilyMeta[] = [
  {
    family: 'editorial_bottom',
    collection: 'Agency',
    legacyComposition: 'EditorialStory',
    nameTr: 'Editoryal Alt',
    nameEn: 'Editorial Bottom',
    descTr: 'Alt gradient, sol hizalı tipografi — günlük story standardı.',
    tags: ['editorial', 'food', 'lifestyle'],
    bestFor: ['daily_moment', 'product_spotlight'],
    sectors: ['cafe_bakery', 'fine_dining', 'beach_club'],
    base: {
      family: 'editorial_bottom',
      textZone: 'bottom_left',
      align: 'left',
      accentLine: 'left_bar',
      gradientStart: 0.52,
    },
    variants: [
      { suffix: 'Classic', suffixTr: 'Klasik', patch: {} },
      { suffix: 'Center', suffixTr: 'Orta', patch: { textZone: 'bottom_center', align: 'center', accentLine: 'above' } },
      { suffix: 'Wide Track', suffixTr: 'Geniş Tracking', patch: { heroTracking: 0.14 } },
      { suffix: 'Light', suffixTr: 'İnce', patch: { heroWeight: 300, heroUppercase: false } },
      { suffix: 'Deep Fade', suffixTr: 'Derin Fade', patch: { gradientStart: 0.42, gradientEnd: 0.88, overlayOpacity: 0.75 } },
      { suffix: 'Soft Fade', suffixTr: 'Yumuşak Fade', patch: { gradientStart: 0.62, gradientEnd: 0.72, overlayOpacity: 0.58 } },
      { suffix: 'Double Rule', suffixTr: 'Çift Çizgi', patch: { accentLine: 'both', accentLineWidth: 0.06 } },
      { suffix: 'No Bar', suffixTr: 'Çizgisiz', patch: { accentLine: 'none' } },
      { suffix: 'Frame', suffixTr: 'Çerçeve', patch: { frame: 'thin' } },
      { suffix: 'Location Off', suffixTr: 'Lokasyonsuz', patch: { showLocation: false } },
    ],
  },
  {
    family: 'editorial_left',
    collection: 'Agency',
    legacyComposition: 'MagazineCoverStory',
    nameTr: 'Magazin Sol',
    nameEn: 'Magazine Left',
    descTr: 'Dev sol headline, dikey kategori — Vogue / Kinfolk estetiği.',
    tags: ['magazine', 'feature', 'chef'],
    bestFor: ['announcement', 'product_spotlight'],
    sectors: ['fine_dining', 'fashion_retail', 'art_gallery'],
    base: {
      family: 'editorial_left',
      collection: 'Agency',
      textZone: 'bottom_left',
      fontPersonality: 'serif_editorial',
      heroWeight: 900,
      heroScale: 1.05,
      gradientStart: 0.35,
      sideBar: 'left',
      categoryVertical: true,
      kenBurnsOrigin: 'center center',
      kenBurnsScale: 1.06,
    },
    variants: [
      { suffix: 'Cover', suffixTr: 'Kapak', patch: {} },
      { suffix: 'Wide', suffixTr: 'Geniş', patch: { heroTracking: 0.08, heroScale: 1.12 } },
      { suffix: 'Tight', suffixTr: 'Sıkı', patch: { heroScale: 0.92, heroTracking: 0.02 } },
      { suffix: 'Noir Wash', suffixTr: 'Noir Yıkama', patch: { duotoneWash: 'primary', duotoneOpacity: 0.42, vignette: 'noir' } },
      { suffix: 'Warm', suffixTr: 'Sıcak', patch: { duotoneWash: 'warm', duotoneOpacity: 0.38 } },
      { suffix: 'Cool', suffixTr: 'Soğuk', patch: { duotoneWash: 'cool', duotoneOpacity: 0.38 } },
      { suffix: 'Double Frame', suffixTr: 'Çift Çerçeve', patch: { frame: 'double' } },
      { suffix: 'Minimal Cat', suffixTr: 'Minimal Etiket', patch: { categoryVertical: false, accentLine: 'above' } },
      { suffix: 'Bold Sans', suffixTr: 'Kalın Sans', patch: { fontPersonality: 'display_bold', heroUppercase: true } },
      { suffix: 'Editorial Serif', suffixTr: 'Serif', patch: { fontPersonality: 'serif_editorial', heroWeight: 400, heroUppercase: false } },
    ],
  },
  {
    family: 'split_panel',
    collection: 'Agency',
    legacyComposition: 'LuxurySplitStory',
    nameTr: 'Split Panel',
    nameEn: 'Luxury Split',
    descTr: 'Foto üst + marka paneli alt — metin asla fotoğraf üstünde değil.',
    tags: ['luxury', 'hotel', 'resort'],
    bestFor: ['product_spotlight', 'social_proof', 'campaign_offer'],
    sectors: ['hotel_resort', 'beach_club', 'fine_dining'],
    base: {
      family: 'split_panel',
      collection: 'Agency',
      backgroundMode: 'split_panel',
      textZone: 'split_panel',
      textOnPhoto: false,
      panelRatio: 0.44,
      overlayOpacity: 0,
      align: 'center',
      accentLine: 'above',
      showLocation: true,
      kenBurnsScale: 1.05,
    },
    variants: [
      { suffix: 'Classic', suffixTr: 'Klasik', patch: {} },
      { suffix: 'Wide Photo', suffixTr: 'Geniş Foto', patch: { panelRatio: 0.38 } },
      { suffix: 'Tall Panel', suffixTr: 'Uzun Panel', patch: { panelRatio: 0.48 } },
      { suffix: 'CTA', suffixTr: 'CTA', patch: { showCtaPill: true } },
      { suffix: 'Left Align', suffixTr: 'Sol Hizalı', patch: { align: 'left', accentLine: 'left_bar' } },
      { suffix: 'Accent Panel', suffixTr: 'Accent Panel', patch: { panelUsesPrimary: false, accentOnCategory: true } },
      { suffix: 'Thin Rule', suffixTr: 'İnce Çizgi', patch: { accentLineWidth: 0.02 } },
      { suffix: 'Bold Type', suffixTr: 'Kalın Tip', patch: { heroWeight: 900, heroScale: 1.08 } },
      { suffix: 'Light Type', suffixTr: 'İnce Tip', patch: { heroWeight: 300, heroUppercase: false } },
      { suffix: 'Inset Frame', suffixTr: 'İç Çerçeve', patch: { frame: 'inset' } },
    ],
  },
  {
    family: 'magazine_cover',
    collection: 'Agency',
    legacyComposition: 'MagazineCoverStory',
    nameTr: 'Kapak Dev Tip',
    nameEn: 'Cover Giant Type',
    descTr: 'Tam ekran kapak estetiği — dev headline, sinematik pan.',
    tags: ['cover', 'editorial', 'brand'],
    bestFor: ['announcement', 'educational'],
    sectors: ['fashion_retail', 'art_gallery', 'music_venue'],
    base: {
      family: 'magazine_cover',
      collection: 'Agency',
      fontPersonality: 'display_bold',
      heroWeight: 900,
      heroScale: 1.12,          // slightly larger for more commanding cover feel
      heroTracking: 0,           // let editorialTracking() auto-apply negative tracking
      gradientStart: 0.32,       // deeper engagement — brand tint starts higher
      overlayOpacity: 0.68,
      kenBurnsScale: 1.08,
      kenBurnsOrigin: '50% 28%', // upper-third focal — face/product hero placement
      vignette: 'soft',
      sideBar: 'left',
      accentLine: 'above',        // above accent bar — magazine header convention
    },
    variants: [
      // Variant 01 — Composition A: Classic bottom-left editorial (default)
      { suffix: 'Hero', suffixTr: 'Hero', patch: {} },
      // Variant 02 — Composition B: Centered for announcement/event
      { suffix: 'Stacked', suffixTr: 'Yığılmış', patch: { textZone: 'bottom_center', align: 'center', heroTracking: 0.02 } },
      // Variant 03 — Composition C: Right-aligned for RTL-friendly or contrast layouts
      { suffix: 'Asymmetric', suffixTr: 'Asimetrik', patch: { textZone: 'bottom_right', align: 'right', sideBar: 'none' } },
      { suffix: 'Vignette', suffixTr: 'Vignette', patch: { vignette: 'radial', overlayOpacity: 0.72 } },
      { suffix: 'Noir', suffixTr: 'Noir', patch: { vignette: 'noir', duotoneWash: 'primary', overlayOpacity: 0.78 } },
      { suffix: 'Gold Accent', suffixTr: 'Altın', patch: { accentOnCategory: true, accentLine: 'both' } },
      { suffix: 'Sans Clean', suffixTr: 'Temiz Sans', patch: { fontPersonality: 'sans_modern', heroWeight: 800 } },
      { suffix: 'Serif Luxe', suffixTr: 'Serif Lüks', patch: { fontPersonality: 'serif_editorial', heroUppercase: false, heroWeight: 700 } },
      { suffix: 'Compact', suffixTr: 'Kompakt', patch: { heroScale: 0.88 } },
      { suffix: 'Oversized', suffixTr: 'Dev', patch: { heroScale: 1.22, heroWeight: 900 } },
    ],
  },
  {
    family: 'cinematic_center',
    collection: 'Cinematic',
    legacyComposition: 'CinematicStory',
    nameTr: 'Sinematik Merkez',
    nameEn: 'Cinematic Center',
    descTr: 'Ortalanmış minimal tip — atmosfer ve manzara storyleri.',
    tags: ['sunset', 'atmosphere', 'minimal'],
    bestFor: ['daily_moment', 'invitation'],
    sectors: ['beach_club', 'hotel_resort', 'marina'],
    base: {
      family: 'cinematic_center',
      collection: 'Cinematic',
      textZone: 'center',
      align: 'center',
      heroWeight: 700,
      heroUppercase: true,
      heroTracking: 0,           // auto-editorial negative tracking for weight 700+
      accentLine: 'none',
      overlayOpacity: 0.74,
      gradientStart: 0.38,       // deeper start — earlier brand ownership of bottom zone
      gradientEnd: 0.78,
      showLocation: true,
      kenBurnsOrigin: '50% 38%', // tighter upper third — cinematic convention
      kenBurnsScale: 1.06,
    },
    variants: [
      // Variant 01 — Composition A: Classic centered (default)
      { suffix: 'Horizon', suffixTr: 'Ufuk', patch: {} },
      // Variant 02 — Composition B: Whisper / luxury light type
      { suffix: 'Whisper', suffixTr: 'Fısıltı', patch: { heroWeight: 300, heroUppercase: false, heroTracking: 0.08 } },
      // Variant 03 — Composition C: Impact / bold campaign
      { suffix: 'Bold', suffixTr: 'Kalın', patch: { fontPersonality: 'display_bold', heroWeight: 900, overlayOpacity: 0.80 } },
      { suffix: 'Bottom', suffixTr: 'Alt', patch: { textZone: 'bottom_center' } },
      { suffix: 'Top', suffixTr: 'Üst', patch: { textZone: 'top_center' } },
      { suffix: 'Deep Vignette', suffixTr: 'Derin Vignette', patch: { vignette: 'radial', overlayOpacity: 0.82 } },
      { suffix: 'Cool Wash', suffixTr: 'Soğuk', patch: { duotoneWash: 'cool' } },
      { suffix: 'Warm Wash', suffixTr: 'Sıcak', patch: { duotoneWash: 'warm' } },
      { suffix: 'No Location', suffixTr: 'Lokasyonsuz', patch: { showLocation: false } },
      { suffix: 'Wide Track', suffixTr: 'Geniş', patch: { heroTracking: 0.28 } },
    ],
  },
  {
    family: 'campaign_hero',
    collection: 'Campaign',
    legacyComposition: 'CampaignHeroStory',
    nameTr: 'Kampanya Hero',
    nameEn: 'Campaign Hero',
    descTr: 'Merkez mega headline + offer pill — promosyon ve lansman.',
    tags: ['campaign', 'offer', 'promo'],
    bestFor: ['campaign_offer', 'announcement'],
    sectors: ['retail', 'nightclub', 'fitness'],
    base: {
      family: 'campaign_hero',
      collection: 'Campaign',
      textZone: 'center',
      align: 'center',
      fontPersonality: 'display_bold',
      heroWeight: 900,
      heroScale: 1.05,
      showCtaPill: true,
      overlayOpacity: 0.74,
      gradientStart: 0.4,
      gradientEnd: 0.85,
      colorPolicy: { headline: 'accent', subtitle: 'text', category: 'accent', overlay: 'primary' },
    },
    variants: [
      { suffix: 'Offer', suffixTr: 'Teklif', patch: {} },
      { suffix: 'Launch', suffixTr: 'Lansman', patch: { accentLine: 'above', heroUppercase: true } },
      { suffix: 'Flash', suffixTr: 'Flaş', patch: { duotoneWash: 'accent', duotoneOpacity: 0.45, fontPersonality: 'graphic_pop', headlineTreatment: 'bubble', heroWeight: 900 } },
      { suffix: 'Dark', suffixTr: 'Koyu', patch: { vignette: 'noir', overlayOpacity: 0.8 } },
      { suffix: 'Light Hero', suffixTr: 'İnce', patch: { heroWeight: 600, heroUppercase: false } },
      { suffix: 'Bottom Stack', suffixTr: 'Alt Yığın', patch: { textZone: 'bottom_center' } },
      { suffix: 'Frame', suffixTr: 'Çerçeve', patch: { frame: 'thin' } },
      { suffix: 'No CTA', suffixTr: 'CTA Yok', patch: { showCtaPill: false } },
      { suffix: 'Double Accent', suffixTr: 'Çift Accent', patch: { accentLine: 'both' } },
      { suffix: 'Compact', suffixTr: 'Kompakt', patch: { heroScale: 0.9 } },
    ],
  },
  {
    family: 'gallery_series',
    collection: 'Agency',
    legacyComposition: 'GallerySeriesStory',
    nameTr: 'Galeri Serisi',
    nameEn: 'Gallery Series',
    descTr: '2–3 fotoğraf + alt panel — social proof ve menü showcase.',
    tags: ['gallery', 'social_proof', 'multi_photo'],
    bestFor: ['social_proof', 'product_spotlight'],
    sectors: ['beach_club', 'fine_dining', 'hotel_resort'],
    base: {
      family: 'gallery_series',
      collection: 'Agency',
      backgroundMode: 'split_panel',
      textZone: 'split_panel',
      textOnPhoto: false,
      panelRatio: 0.46,
      overlayOpacity: 0,
      align: 'center',
      accentLine: 'above',
      showLocation: true,
    },
    variants: [
      { suffix: 'Dual', suffixTr: 'Çift', patch: {} },
      { suffix: 'Triple Strip', suffixTr: 'Üç Şerit', patch: { panelRatio: 0.42 } },
      { suffix: 'Wide Panel', suffixTr: 'Geniş Panel', patch: { panelRatio: 0.5 } },
      { suffix: 'Left Type', suffixTr: 'Sol Tip', patch: { align: 'left', accentLine: 'left_bar' } },
      { suffix: 'CTA', suffixTr: 'CTA', patch: { showCtaPill: true } },
      { suffix: 'Minimal', suffixTr: 'Minimal', patch: { accentLine: 'none', heroWeight: 600 } },
      { suffix: 'Bold', suffixTr: 'Kalın', patch: { heroWeight: 900, heroScale: 1.06 } },
      { suffix: 'Accent Panel', suffixTr: 'Accent', patch: { panelUsesPrimary: false } },
      { suffix: 'Serif', suffixTr: 'Serif', patch: { fontPersonality: 'serif_editorial' } },
      { suffix: 'Display', suffixTr: 'Display', patch: { fontPersonality: 'display_bold' } },
    ],
  },
  {
    family: 'frosted_glass',
    collection: 'Modern',
    legacyComposition: 'EditorialStory',
    nameTr: 'Buzlu Cam',
    nameEn: 'Frosted Glass',
    descTr: 'Glassmorphism kart — modern SaaS / lifestyle estetiği.',
    tags: ['modern', 'glass', 'clean'],
    bestFor: ['daily_moment', 'educational'],
    sectors: ['co_working', 'tech_startup', 'wellness_spa'],
    base: {
      family: 'frosted_glass',
      collection: 'Modern',
      frostedCard: true,
      frostedY: 0.58,
      textZone: 'bottom_center',
      align: 'center',
      fontPersonality: 'sans_modern',
      heroWeight: 700,
      overlayOpacity: 0.55,
      gradientStart: 0.5,
      accentLine: 'above',
    },
    variants: [
      { suffix: 'Card', suffixTr: 'Kart', patch: {} },
      { suffix: 'High', suffixTr: 'Yüksek', patch: { frostedY: 0.52 } },
      { suffix: 'Low', suffixTr: 'Alçak', patch: { frostedY: 0.68 } },
      { suffix: 'Left', suffixTr: 'Sol', patch: { textZone: 'bottom_left', align: 'left' } },
      { suffix: 'Bold', suffixTr: 'Kalın', patch: { heroWeight: 900, fontPersonality: 'display_bold' } },
      { suffix: 'Light', suffixTr: 'İnce', patch: { heroWeight: 300, heroUppercase: false } },
      { suffix: 'Frame', suffixTr: 'Çerçeve', patch: { frame: 'thin' } },
      { suffix: 'Cool', suffixTr: 'Soğuk', patch: { duotoneWash: 'cool', duotoneOpacity: 0.3 } },
      { suffix: 'Warm', suffixTr: 'Sıcak', patch: { duotoneWash: 'warm', duotoneOpacity: 0.3 } },
      { suffix: 'No Frost', suffixTr: 'Şeffaf', patch: { frostedCard: false, overlayOpacity: 0.65 } },
    ],
  },
  {
    family: 'bold_impact',
    collection: 'Modern',
    legacyComposition: 'CampaignHeroStory',
    nameTr: 'Bold Impact',
    nameEn: 'Bold Impact',
    descTr: 'Tam ekran dev tip — Dribbble / Awwwards poster enerjisi.',
    tags: ['bold', 'impact', 'poster'],
    bestFor: ['campaign_offer', 'announcement'],
    sectors: ['nightclub', 'fitness', 'music_venue'],
    base: {
      family: 'bold_impact',
      collection: 'Modern',
      fontPersonality: 'display_bold',
      heroWeight: 900,
      heroScale: 1.15,
      heroUppercase: true,
      heroTracking: 0.02,
      textZone: 'center',
      align: 'center',
      overlayOpacity: 0.7,
      gradientStart: 0.35,
      vignette: 'radial',
      colorPolicy: { headline: 'accent', subtitle: 'text', category: 'accent', overlay: 'accent' },
    },
    variants: [
      { suffix: 'Poster', suffixTr: 'Poster', patch: {} },
      { suffix: 'Flush Bottom', suffixTr: 'Alt Flush', patch: { textZone: 'bottom_center', heroScale: 1.08 } },
      { suffix: 'Stacked', suffixTr: 'Yığılmış', patch: { heroTracking: 0.04, heroScale: 1.0, fontPersonality: 'graphic_pop', headlineTreatment: 'bubble', heroUppercase: false } },
      { suffix: 'Neon Accent', suffixTr: 'Neon', patch: { duotoneWash: 'accent', duotoneOpacity: 0.5, accentOnCategory: true } },
      { suffix: 'Noir', suffixTr: 'Noir', patch: { vignette: 'noir', overlayOpacity: 0.82 } },
      { suffix: 'Outline Feel', suffixTr: 'Outline', patch: { accentLine: 'underline', heroTracking: 0.12 } },
      { suffix: 'Left Anchor', suffixTr: 'Sol', patch: { textZone: 'bottom_left', align: 'left' } },
      { suffix: 'Compact', suffixTr: 'Kompakt', patch: { heroScale: 0.95 } },
      { suffix: 'Mega', suffixTr: 'Mega', patch: { heroScale: 1.22 } },
      { suffix: 'CTA', suffixTr: 'CTA', patch: { showCtaPill: true } },
    ],
  },
  {
    family: 'noir_editorial',
    collection: 'Agency',
    legacyComposition: 'CinematicStory',
    nameTr: 'Noir Editoryal',
    nameEn: 'Noir Editorial',
    descTr: 'Koyu, sinematik, lüks gece estetiği — bar & fine dining.',
    tags: ['noir', 'night', 'luxury'],
    bestFor: ['invitation', 'event', 'product_spotlight'],
    sectors: ['cocktail_bar', 'wine_bar', 'steakhouse'],
    base: {
      family: 'noir_editorial',
      collection: 'Agency',
      fontPersonality: 'serif_editorial',
      heroWeight: 400,
      heroUppercase: false,
      vignette: 'noir',
      duotoneWash: 'primary',
      duotoneOpacity: 0.48,
      overlayOpacity: 0.78,
      gradientStart: 0.3,
      gradientEnd: 0.88,
      textZone: 'bottom_left',
      accentLine: 'above',
      categoryTracking: 0.18,
    },
    variants: [
      { suffix: 'Classic', suffixTr: 'Klasik', patch: {} },
      { suffix: 'Center', suffixTr: 'Merkez', patch: { textZone: 'center', align: 'center' } },
      { suffix: 'Gold Line', suffixTr: 'Altın Çizgi', patch: { accentLine: 'both', accentOnCategory: true } },
      { suffix: 'Vertical Cat', suffixTr: 'Dikey Etiket', patch: { categoryVertical: true, sideBar: 'left' } },
      { suffix: 'Whisper', suffixTr: 'Fısıltı', patch: { heroWeight: 300, subtitleItalic: true } },
      { suffix: 'Bold Contrast', suffixTr: 'Kontrast', patch: { fontPersonality: 'display_bold', heroWeight: 900, heroUppercase: true } },
      { suffix: 'Deep', suffixTr: 'Derin', patch: { overlayOpacity: 0.85, vignette: 'noir' } },
      { suffix: 'Warm Noir', suffixTr: 'Sıcak Noir', patch: { duotoneWash: 'warm' } },
      { suffix: 'Cool Noir', suffixTr: 'Soğuk Noir', patch: { duotoneWash: 'cool' } },
      { suffix: 'Frame', suffixTr: 'Çerçeve', patch: { frame: 'double' } },
    ],
  },
  // ── Agency collection (Dribbble / Pinterest / Envato patterns) ─────────────
  {
    family: 'event_ticket',
    collection: 'Agency',
    legacyComposition: 'EventAnnouncementStory',
    nameTr: 'Etkinlik Bileti',
    nameEn: 'Event Ticket',
    descTr: 'Inset çerçeve, tarih badge, CTA pill — Linearity / Envato event story.',
    tags: ['event', 'ticket', 'announcement', 'cta'],
    bestFor: ['event', 'invitation', 'announcement'],
    sectors: ['nightclub', 'music_venue', 'event_venue', 'beach_club'],
    base: {
      family: 'event_ticket',
      collection: 'Agency',
      fontPersonality: 'display_bold',
      heroWeight: 900,
      heroUppercase: true,
      showCtaPill: true,
      overlayOpacity: 0.72,
      gradientStart: 0.35,
      frame: 'thin',
      textZone: 'bottom_center',
      align: 'center',
      colorPolicy: { headline: 'accent', subtitle: 'text', category: 'accent', overlay: 'primary' },
    },
    variants: [
      { suffix: 'Classic', suffixTr: 'Klasik', patch: {} },
      { suffix: 'Serif', suffixTr: 'Serif', patch: { fontPersonality: 'serif_editorial', heroWeight: 700, heroUppercase: false } },
      { suffix: 'Neon', suffixTr: 'Neon', patch: { duotoneWash: 'accent', duotoneOpacity: 0.4 } },
      { suffix: 'Dark', suffixTr: 'Koyu', patch: { overlayOpacity: 0.82, vignette: 'noir' } },
      { suffix: 'Minimal CTA', suffixTr: 'Minimal CTA', patch: { showCtaPill: true, heroScale: 0.95 } },
      { suffix: 'Wide', suffixTr: 'Geniş', patch: { heroTracking: 0.1 } },
      { suffix: 'Gold Frame', suffixTr: 'Altın', patch: { frame: 'double', accentOnCategory: true } },
      { suffix: 'Modern', suffixTr: 'Modern', patch: { fontPersonality: 'sans_modern', heroWeight: 800 } },
    ],
  },
  {
    family: 'diptych_collage',
    collection: 'Agency',
    legacyComposition: 'GallerySeriesStory',
    nameTr: 'Diptych Kolaj',
    nameEn: 'Diptych Collage',
    descTr: 'İki fotoğraf yan yana + marka paneli — menü & social proof.',
    tags: ['dual', 'collage', 'gallery', 'multi_photo'],
    bestFor: ['social_proof', 'product_spotlight', 'daily_moment'],
    sectors: ['fine_dining', 'beach_club', 'cafe_bakery'],
    base: {
      family: 'diptych_collage',
      collection: 'Agency',
      backgroundMode: 'split_panel',
      textZone: 'split_panel',
      textOnPhoto: false,
      panelRatio: 0.44,
      fontPersonality: 'serif_editorial',
      showLocation: true,
      align: 'left',
    },
    variants: [
      { suffix: 'Dual', suffixTr: 'Çift', patch: {} },
      { suffix: 'CTA', suffixTr: 'CTA', patch: { showCtaPill: true } },
      { suffix: 'Bold', suffixTr: 'Kalın', patch: { fontPersonality: 'display_bold', heroWeight: 900 } },
      { suffix: 'Serif', suffixTr: 'Serif', patch: { fontPersonality: 'serif_editorial', heroUppercase: false } },
      { suffix: 'Sans', suffixTr: 'Sans', patch: { fontPersonality: 'sans_modern' } },
      { suffix: 'Accent Bar', suffixTr: 'Accent', patch: { accentLine: 'above' } },
      { suffix: 'Compact', suffixTr: 'Kompakt', patch: { panelRatio: 0.38, heroScale: 0.9 } },
      { suffix: 'Wide Panel', suffixTr: 'Geniş Panel', patch: { panelRatio: 0.48 } },
    ],
  },
  {
    family: 'minimal_luxury',
    collection: 'Agency',
    legacyComposition: 'LuxurySplitStory',
    nameTr: 'Minimal Lüks',
    nameEn: 'Minimal Luxury',
    descTr: 'Double inset frame, serif hero, nefes alan boşluk — otel & fine dining.',
    tags: ['luxury', 'hotel', 'minimal', 'editorial'],
    bestFor: ['product_spotlight', 'invitation', 'daily_moment'],
    sectors: ['hotel_resort', 'fine_dining', 'wellness_spa', 'boutique_hotel'],
    base: {
      family: 'minimal_luxury',
      collection: 'Agency',
      fontPersonality: 'serif_editorial',
      heroWeight: 400,
      heroUppercase: false,
      heroTracking: 0.06,
      frame: 'double',
      overlayOpacity: 0.55,
      gradientStart: 0.48,
      vignette: 'soft',
      showLocation: true,
      align: 'left',
    },
    variants: [
      { suffix: 'Classic', suffixTr: 'Klasik', patch: {} },
      { suffix: 'Center', suffixTr: 'Merkez', patch: { align: 'center', textZone: 'bottom_center' } },
      { suffix: 'Bodoni', suffixTr: 'Bodoni', patch: { fontPersonality: 'brand', heroWeight: 600 } },
      { suffix: 'Whisper', suffixTr: 'Fısıltı', patch: { heroWeight: 300, subtitleItalic: true } },
      { suffix: 'Gold', suffixTr: 'Altın', patch: { accentOnCategory: true, accentLine: 'above' } },
      { suffix: 'Deep', suffixTr: 'Derin', patch: { overlayOpacity: 0.68, vignette: 'radial' } },
      { suffix: 'No Location', suffixTr: 'Lokasyonsuz', patch: { showLocation: false } },
      { suffix: 'Wide', suffixTr: 'Geniş', patch: { heroScale: 1.12, heroTracking: 0.1 } },
    ],
  },
  {
    family: 'mosaic_pinterest',
    collection: 'Agency',
    legacyComposition: 'GallerySeriesStory',
    nameTr: 'Mosaic Grid',
    nameEn: 'Pinterest Mosaic',
    descTr: '3 karo foto grid + marka renk bandı — Idea Pin / Pinterest estetiği.',
    tags: ['mosaic', 'pinterest', 'triple', 'multi_photo'],
    bestFor: ['social_proof', 'product_spotlight', 'educational'],
    sectors: ['beach_club', 'fashion_retail', 'hotel_resort', 'brunch'],
    base: {
      family: 'mosaic_pinterest',
      collection: 'Agency',
      fontPersonality: 'sans_modern',
      heroWeight: 800,
      panelUsesPrimary: true,
      showCtaPill: true,
      align: 'left',
      textOnPhoto: false,
    },
    variants: [
      { suffix: 'Grid', suffixTr: 'Grid', patch: {} },
      { suffix: 'Serif', suffixTr: 'Serif', patch: { fontPersonality: 'serif_editorial' } },
      { suffix: 'Bold', suffixTr: 'Kalın', patch: { fontPersonality: 'display_bold', heroUppercase: true } },
      { suffix: 'No CTA', suffixTr: 'CTA Yok', patch: { showCtaPill: false } },
      { suffix: 'Accent', suffixTr: 'Accent', patch: { accentOnCategory: true } },
      { suffix: 'Compact', suffixTr: 'Kompakt', patch: { heroScale: 0.88 } },
      { suffix: 'Light', suffixTr: 'İnce', patch: { heroWeight: 600, heroUppercase: false } },
      { suffix: 'Editorial', suffixTr: 'Editoryal', patch: { fontPersonality: 'brand', heroWeight: 700 } },
    ],
  },
  {
    family: 'asymmetric_editorial',
    collection: 'Agency',
    legacyComposition: 'MagazineCoverStory',
    nameTr: 'Asimetrik Panel',
    nameEn: 'Asymmetric Editorial',
    descTr: 'ORZA tarzı renk bloğu + foto — fashion & lifestyle editorial.',
    tags: ['asymmetric', 'editorial', 'orza', 'panel'],
    bestFor: ['announcement', 'product_spotlight', 'campaign_offer'],
    sectors: ['fashion_retail', 'art_gallery', 'cocktail_bar', 'jewelry'],
    base: {
      family: 'asymmetric_editorial',
      collection: 'Agency',
      fontPersonality: 'serif_editorial',
      heroWeight: 700,
      panelUsesPrimary: true,
      overlayOpacity: 0,
      kenBurnsScale: 1.07,
      align: 'left',
    },
    variants: [
      { suffix: 'Classic', suffixTr: 'Klasik', patch: {} },
      { suffix: 'Bold', suffixTr: 'Kalın', patch: { fontPersonality: 'display_bold', heroWeight: 900, heroUppercase: true } },
      { suffix: 'Script', suffixTr: 'Script', patch: { fontPersonality: 'script', heroUppercase: false } },
      { suffix: 'Noir', suffixTr: 'Noir', patch: {
        duotoneWash: 'primary', duotoneOpacity: 0.22, vignette: 'soft',
        gradientStart: 0.55, gradientEnd: 0.88, overlayOpacity: 0.38,
      } },
      { suffix: 'Warm', suffixTr: 'Sıcak', patch: { duotoneWash: 'warm' } },
      { suffix: 'Cool', suffixTr: 'Soğuk', patch: { duotoneWash: 'cool' } },
      { suffix: 'Sans', suffixTr: 'Sans', patch: { fontPersonality: 'sans_modern' } },
      { suffix: 'Mega', suffixTr: 'Mega', patch: { heroScale: 1.1 } },
    ],
  },
  {
    family: 'polaroid_single',
    collection: 'Agency',
    legacyComposition: 'SpecStory',
    nameTr: 'Polaroid Tekli',
    nameEn: 'Polaroid Single',
    descTr: 'Ortada tek büyük polaroid — mekan hero fotoğrafı, alt tipografi.',
    tags: ['polaroid', 'single', 'hero', 'venue'],
    bestFor: ['daily_moment', 'social_proof', 'product_spotlight'],
    sectors: ['beach_club', 'cafe_bakery', 'hotel_resort', 'cocktail_bar', 'brunch'],
    base: {
      family: 'polaroid_single',
      collection: 'Agency',
      fontPersonality: 'serif_editorial',
      heroWeight: 700,
      heroUppercase: false,
      overlayOpacity: 0,
      align: 'left',
      vignette: 'soft',
    },
    variants: [
      { suffix: 'Classic', suffixTr: 'Klasik', patch: {} },
      { suffix: 'Serif', suffixTr: 'Serif', patch: { fontPersonality: 'serif_editorial', heroWeight: 600 } },
      { suffix: 'Bold', suffixTr: 'Kalın', patch: { fontPersonality: 'display_bold', heroUppercase: true, heroWeight: 800 } },
      { suffix: 'Warm', suffixTr: 'Sıcak', patch: { duotoneWash: 'warm', duotoneOpacity: 0.22 } },
      { suffix: 'Minimal', suffixTr: 'Minimal', patch: { heroWeight: 400, heroScale: 0.95 } },
      { suffix: 'Sans', suffixTr: 'Sans', patch: { fontPersonality: 'sans_modern' } },
      { suffix: 'Script', suffixTr: 'Script', patch: { fontPersonality: 'script', heroUppercase: false } },
      { suffix: 'Display', suffixTr: 'Display', patch: { fontPersonality: 'display_bold', heroScale: 1.05 } },
    ],
  },
  {
    family: 'polaroid_stack',
    collection: 'Agency',
    legacyComposition: 'GallerySeriesStory',
    nameTr: 'Polaroid Çoklu',
    nameEn: 'Polaroid Stack',
    descTr: 'Eğik polaroid kareler — tactile editorial, 2–3 fotoğraf.',
    tags: ['polaroid', 'stack', 'tactile', 'multi_photo'],
    bestFor: ['social_proof', 'daily_moment', 'educational'],
    sectors: ['cafe_bakery', 'patisserie', 'brunch', 'art_gallery', 'beach_club'],
    base: {
      family: 'polaroid_stack',
      collection: 'Agency',
      fontPersonality: 'brand',
      heroWeight: 800,
      overlayOpacity: 0,
      align: 'left',
    },
    variants: [
      { suffix: 'Classic', suffixTr: 'Klasik', patch: {} },
      { suffix: 'Serif', suffixTr: 'Serif', patch: { fontPersonality: 'serif_editorial', heroWeight: 600 } },
      { suffix: 'Bold', suffixTr: 'Kalın', patch: { fontPersonality: 'display_bold' } },
      { suffix: 'Warm', suffixTr: 'Sıcak', patch: { duotoneWash: 'warm', duotoneOpacity: 0.25 } },
      { suffix: 'Minimal', suffixTr: 'Minimal', patch: { heroWeight: 600, heroUppercase: false } },
      { suffix: 'Display', suffixTr: 'Display', patch: { fontPersonality: 'display_bold', heroUppercase: true } },
      { suffix: 'Script', suffixTr: 'Script', patch: { fontPersonality: 'script' } },
      { suffix: 'Modern', suffixTr: 'Modern', patch: { fontPersonality: 'sans_modern' } },
    ],
  },
  {
    family: 'vibe_fullscreen',
    collection: 'Agency',
    legacyComposition: 'SpecStory',
    nameTr: 'Vibe Fullscreen',
    nameEn: 'Vibe Fullscreen',
    descTr: 'Dev tipografi + mesh gradient + dairesel hero — 2025 social native.',
    tags: ['vibe', 'fullscreen', 'mesh', 'premium'],
    bestFor: ['daily_moment', 'product_spotlight', 'campaign_offer'],
    sectors: ['beach_club', 'hotel_resort', 'fashion_retail', 'cocktail_bar'],
    base: {
      family: 'vibe_fullscreen',
      collection: 'Agency',
      fontPersonality: 'display_bold',
      heroWeight: 900,
      heroUppercase: true,
      heroScale: 1.1,
      showLocation: true,
      overlayOpacity: 0,
      vignette: 'soft',
      colorPolicy: { headline: 'accent', subtitle: 'text', category: 'primary', overlay: 'accent' },
    },
    variants: [
      { suffix: 'Classic', suffixTr: 'Klasik', patch: {} },
      { suffix: 'Serif', suffixTr: 'Serif', patch: { fontPersonality: 'serif_editorial', heroUppercase: false } },
      { suffix: 'Minimal', suffixTr: 'Minimal', patch: { heroWeight: 700, heroScale: 1.05 } },
      { suffix: 'Bold', suffixTr: 'Kalın', patch: { heroScale: 1.15, heroTracking: 0.02, fontPersonality: 'neo_grotesk', headlineTreatment: 'sticker', heroUppercase: false } },
      { suffix: 'Warm', suffixTr: 'Sıcak', patch: { duotoneWash: 'warm', duotoneOpacity: 0.2 } },
      { suffix: 'Cool', suffixTr: 'Soğuk', patch: { duotoneWash: 'cool', duotoneOpacity: 0.2 } },
      { suffix: 'No Loc', suffixTr: 'Lokasyonsuz', patch: { showLocation: false } },
      { suffix: 'Wide', suffixTr: 'Geniş', patch: { heroTracking: 0.08 } },
    ],
  },
  {
    family: 'bento_story',
    collection: 'Agency',
    legacyComposition: 'GallerySeriesStory',
    nameTr: 'Bento Grid',
    nameEn: 'Bento Grid',
    descTr: 'Asimetrik 4 hücre grid + glass tipografi bandı — Pinterest/IG carousel vibe.',
    tags: ['bento', 'grid', 'multi_photo', '2025'],
    bestFor: ['social_proof', 'product_spotlight', 'educational'],
    sectors: ['fine_dining', 'brunch', 'hotel_resort', 'cafe_bakery'],
    base: {
      family: 'bento_story',
      collection: 'Agency',
      fontPersonality: 'sans_modern',
      heroWeight: 800,
      panelUsesPrimary: true,
      align: 'left',
    },
    variants: [
      { suffix: 'Grid', suffixTr: 'Grid', patch: {} },
      { suffix: 'Serif', suffixTr: 'Serif', patch: { fontPersonality: 'serif_editorial' } },
      { suffix: 'Bold', suffixTr: 'Kalın', patch: { fontPersonality: 'display_bold' } },
      { suffix: 'Editorial', suffixTr: 'Editoryal', patch: { fontPersonality: 'brand' } },
      { suffix: 'Compact', suffixTr: 'Kompakt', patch: { heroScale: 0.85 } },
      { suffix: 'Accent', suffixTr: 'Accent', patch: { accentOnCategory: true } },
      { suffix: 'Light', suffixTr: 'İnce', patch: { heroWeight: 700, fontPersonality: 'graphic_pop', headlineTreatment: 'bubble', heroUppercase: false } },
      { suffix: 'Mega', suffixTr: 'Mega', patch: { heroScale: 0.95, heroWeight: 900 } },
    ],
  },
  {
    family: 'neon_night',
    collection: 'Agency',
    legacyComposition: 'EventAnnouncementStory',
    nameTr: 'Neon Night',
    nameEn: 'Neon Night',
    descTr: 'Mesh + neon glow + pulse — nightclub / DJ / rooftop 2025.',
    tags: ['neon', 'night', 'glow', 'event'],
    bestFor: ['event', 'invitation', 'announcement'],
    sectors: ['nightclub', 'music_venue', 'rooftop_bar', 'beach_club'],
    base: {
      family: 'neon_night',
      collection: 'Agency',
      fontPersonality: 'display_bold',
      heroWeight: 900,
      heroUppercase: true,
      showCtaPill: true,
      duotoneWash: 'accent',
      duotoneOpacity: 0.35,
      overlayOpacity: 0,
      colorPolicy: { headline: 'accent', subtitle: 'text', category: 'accent', overlay: 'accent' },
    },
    variants: [
      { suffix: 'Pulse', suffixTr: 'Pulse', patch: {} },
      { suffix: 'Electric', suffixTr: 'Elektrik', patch: { duotoneOpacity: 0.5 } },
      { suffix: 'Deep', suffixTr: 'Derin', patch: { vignette: 'noir' } },
      { suffix: 'Sans', suffixTr: 'Sans', patch: { fontPersonality: 'sans_modern' } },
      { suffix: 'Wide', suffixTr: 'Geniş', patch: { heroTracking: 0.12 } },
      { suffix: 'Minimal CTA', suffixTr: 'Minimal CTA', patch: { showCtaPill: true, heroScale: 0.92 } },
      { suffix: 'Cool', suffixTr: 'Soğuk', patch: { duotoneWash: 'cool' } },
      { suffix: 'Warm', suffixTr: 'Sıcak', patch: { duotoneWash: 'warm' } },
    ],
  },
  {
    family: 'quote_card',
    collection: 'Agency',
    legacyComposition: 'SpecStory',
    nameTr: 'Quote Card',
    nameEn: 'Quote Card',
    descTr: 'Dev tırnak + frosted testimonial kartı — üst logo, alt lockup.',
    tags: ['quote', 'review', 'social_proof', 'logo'],
    bestFor: ['social_proof', 'educational', 'daily_moment'],
    sectors: ['fine_dining', 'hotel_resort', 'wellness_spa', 'beach_club', 'cafe_bakery'],
    base: {
      family: 'quote_card',
      collection: 'Agency',
      fontPersonality: 'serif_editorial',
      heroWeight: 400,
      heroUppercase: false,
      heroScale: 1.0,
      subtitleItalic: true,
      overlayOpacity: 0.72,
      frostedCard: true,
      align: 'center',
      textZone: 'bottom_center',
    },
    variants: [
      { suffix: 'Classic', suffixTr: 'Klasik', patch: {} },
      { suffix: 'Serif', suffixTr: 'Serif', patch: { fontPersonality: 'brand', heroWeight: 400 } },
      { suffix: 'Bold', suffixTr: 'Kalın', patch: { fontPersonality: 'display_bold', heroWeight: 700 } },
      { suffix: 'Whisper', suffixTr: 'Fısıltı', patch: { heroWeight: 300, heroScale: 0.92 } },
      { suffix: 'Bubble', suffixTr: 'Bubble', patch: { fontPersonality: 'graphic_pop', headlineTreatment: 'bubble', heroWeight: 800, heroUppercase: false, heroScale: 1.02 } },
      { suffix: 'Minimal', suffixTr: 'Minimal', patch: { overlayOpacity: 0.6, vignette: 'soft' } },
      { suffix: 'Editorial', suffixTr: 'Editoryal', patch: { fontPersonality: 'serif_editorial', heroTracking: 0.06 } },
      { suffix: 'Sticker', suffixTr: 'Sticker', patch: { fontPersonality: 'neo_grotesk', headlineTreatment: 'sticker', heroWeight: 800, heroScale: 1.05, heroUppercase: false } },
    ],
  },
  {
    family: 'location_pin',
    collection: 'Agency',
    legacyComposition: 'SpecStory',
    nameTr: 'Location Pin',
    nameEn: 'Location Pin',
    descTr: 'IG-native konum kartı — inline logo + pin + yol tarifi CTA.',
    tags: ['location', 'pin', 'maps', 'logo', 'cta'],
    bestFor: ['daily_moment', 'invitation', 'announcement'],
    sectors: ['beach_club', 'hotel_resort', 'cafe_bakery', 'cocktail_bar', 'boutique_hotel'],
    base: {
      family: 'location_pin',
      collection: 'Agency',
      fontPersonality: 'sans_modern',
      heroWeight: 800,
      heroUppercase: true,
      showLocation: true,
      showCtaPill: true,
      kenBurnsScale: 1.08,
      overlayOpacity: 0.55,
      align: 'left',
      textZone: 'top_center',
    },
    variants: [
      { suffix: 'Classic', suffixTr: 'Klasik', patch: {} },
      { suffix: 'Serif', suffixTr: 'Serif', patch: { fontPersonality: 'serif_editorial', heroUppercase: false } },
      { suffix: 'Bold', suffixTr: 'Kalın', patch: { fontPersonality: 'display_bold', heroWeight: 900 } },
      { suffix: 'Minimal CTA', suffixTr: 'Minimal CTA', patch: { showCtaPill: true, heroScale: 0.9 } },
      { suffix: 'No CTA', suffixTr: 'CTA Yok', patch: { showCtaPill: false } },
      { suffix: 'Warm', suffixTr: 'Sıcak', patch: { duotoneWash: 'warm', duotoneOpacity: 0.2 } },
      { suffix: 'Cool', suffixTr: 'Soğuk', patch: { duotoneWash: 'cool', duotoneOpacity: 0.2 } },
      { suffix: 'Wide', suffixTr: 'Geniş', patch: { heroTracking: 0.08 } },
    ],
  },
  {
    family: 'luxury_kinetic_type',
    collection: 'Agency',
    legacyComposition: 'SpecStory',
    nameTr: 'Luxury Kinetic Type',
    nameEn: 'Luxury Kinetic Type',
    descTr: 'Dev premium tipografi, editorial depth shadow ve sinematik marka sahnesi.',
    tags: ['premium', 'kinetic_type', '3d_text', 'campaign', 'agency'],
    bestFor: ['campaign_offer', 'announcement', 'event'],
    sectors: ['beauty_salon', 'fashion_retail', 'nightclub', 'music_venue', 'agency_services', 'beach_club'],
    base: {
      family: 'luxury_kinetic_type',
      collection: 'Agency',
      fontPersonality: 'display_bold',
      heroWeight: 900,
      heroUppercase: true,
      heroTracking: -0.02,
      heroScale: 1.18,
      gradientStart: 0.22,
      gradientEnd: 0.92,
      overlayOpacity: 0.72,
      kenBurnsOrigin: '50% 34%',
      kenBurnsScale: 1.14,
      vignette: 'radial',
      textZone: 'bottom_center',
      align: 'center',
      accentLine: 'above',
      showCtaPill: true,
      duotoneWash: 'primary',
      duotoneOpacity: 0.28,
      colorPolicy: { headline: 'accent', subtitle: 'text', category: 'accent', overlay: 'primary' },
    },
    variants: [
      { suffix: 'Hero Depth', suffixTr: 'Hero Depth', patch: {} },
      { suffix: 'Neon Edge', suffixTr: 'Neon Edge', patch: { duotoneWash: 'accent', duotoneOpacity: 0.38, headlineTreatment: 'sticker' } },
      { suffix: 'Serif Luxe', suffixTr: 'Serif Lüks', patch: { fontPersonality: 'luxury_serif', heroUppercase: false, heroWeight: 700, heroTracking: 0.02 } },
      { suffix: 'Top Lockup', suffixTr: 'Üst Lockup', patch: { textZone: 'top_center', gradientStart: 0.35, gradientEnd: 0.85 } },
      { suffix: 'Noir Stage', suffixTr: 'Noir Sahne', patch: { vignette: 'noir', overlayOpacity: 0.82, duotoneWash: 'primary' } },
      { suffix: 'Clean Impact', suffixTr: 'Temiz Impact', patch: { fontPersonality: 'neo_grotesk', headlineTreatment: 'flat', heroScale: 1.04 } },
      { suffix: 'Sticker Pop', suffixTr: 'Sticker Pop', patch: { fontPersonality: 'graphic_pop', headlineTreatment: 'sticker', heroUppercase: false, heroScale: 1.08 } },
      { suffix: 'Editorial Wide', suffixTr: 'Editoryal Geniş', patch: { heroTracking: 0.12, accentLine: 'both', showCtaPill: false } },
    ],
  },
  {
    family: 'glassmorphism_showcase',
    collection: 'Agency',
    legacyComposition: 'SpecStory',
    nameTr: 'Glassmorphism Showcase',
    nameEn: 'Glassmorphism Showcase',
    descTr: 'Blur cam panel, floating card ve modern premium sosyal medya kompozisyonu.',
    tags: ['premium', 'glassmorphism', 'showcase', 'modern', 'agency'],
    bestFor: ['daily_moment', 'product_spotlight', 'announcement', 'social_proof'],
    sectors: ['beauty_salon', 'wellness_spa', 'cafe_bakery', 'fine_dining', 'fashion_retail', 'agency_services'],
    base: {
      family: 'glassmorphism_showcase',
      collection: 'Agency',
      fontPersonality: 'neo_grotesk',
      heroWeight: 800,
      heroUppercase: false,
      heroTracking: -0.01,
      heroScale: 1.1,
      gradientStart: 0.2,
      gradientEnd: 0.88,
      overlayOpacity: 0.55,
      kenBurnsOrigin: '52% 42%',
      kenBurnsScale: 1.1,
      vignette: 'soft',
      textZone: 'bottom_left',
      align: 'left',
      accentLine: 'none',
      frostedCard: true,
      showCtaPill: false,
      duotoneWash: 'accent',
      duotoneOpacity: 0.16,
      colorPolicy: { headline: 'accent', subtitle: 'text', category: 'accent', overlay: 'accent' },
    },
    variants: [
      { suffix: 'Floating Card', suffixTr: 'Floating Card', patch: {} },
      { suffix: 'Centered Glass', suffixTr: 'Ortada Cam', patch: { textZone: 'center', align: 'center', heroScale: 0.92 } },
      { suffix: 'Soft Luxury', suffixTr: 'Soft Lüks', patch: { fontPersonality: 'luxury_serif', heroWeight: 600, subtitleItalic: true } },
      { suffix: 'Bold Product', suffixTr: 'Kalın Ürün', patch: { fontPersonality: 'display_bold', heroWeight: 900, heroUppercase: true } },
      { suffix: 'Cool Frost', suffixTr: 'Soğuk Frost', patch: { duotoneWash: 'cool', duotoneOpacity: 0.24 } },
      { suffix: 'Warm Glow', suffixTr: 'Sıcak Glow', patch: { duotoneWash: 'warm', duotoneOpacity: 0.24 } },
      { suffix: 'CTA Panel', suffixTr: 'CTA Panel', patch: { showCtaPill: true, accentLine: 'underline' } },
      { suffix: 'Minimal Premium', suffixTr: 'Minimal Premium', patch: { overlayOpacity: 0.42, showLocation: false, heroScale: 0.86 } },
    ],
  },
  {
    family: 'editorial_product_stage',
    collection: 'Agency',
    legacyComposition: 'SpecStory',
    nameTr: 'Editorial Product Stage',
    nameEn: 'Editorial Product Stage',
    descTr: 'Ürün/venue görselini dergi sahnesine alan premium editorial story.',
    tags: ['premium', 'product_stage', 'editorial', 'venue', 'agency'],
    bestFor: ['product_spotlight', 'campaign_offer', 'social_proof'],
    sectors: ['fine_dining', 'cafe_bakery', 'fashion_retail', 'beauty_salon', 'retail', 'hotel_resort'],
    base: {
      family: 'editorial_product_stage',
      collection: 'Agency',
      fontPersonality: 'fashion_editorial',
      heroWeight: 700,
      heroUppercase: false,
      heroTracking: 0.01,
      heroScale: 1.0,
      gradientStart: 0.3,
      gradientEnd: 0.9,
      overlayOpacity: 0.5,
      kenBurnsOrigin: '50% 42%',
      kenBurnsScale: 1.08,
      vignette: 'soft',
      textZone: 'bottom_left',
      align: 'left',
      accentLine: 'above',
      showLocation: true,
      showCtaPill: true,
      duotoneWash: 'none',
      colorPolicy: { headline: 'primary', subtitle: 'text', category: 'accent', overlay: 'primary' },
    },
    variants: [
      { suffix: 'Stage Left', suffixTr: 'Sol Sahne', patch: {} },
      { suffix: 'Stage Right', suffixTr: 'Sağ Sahne', patch: { textZone: 'bottom_right', align: 'right' } },
      { suffix: 'Magazine Center', suffixTr: 'Magazin Orta', patch: { textZone: 'bottom_center', align: 'center', fontPersonality: 'serif_editorial' } },
      { suffix: 'Dark Gallery', suffixTr: 'Koyu Galeri', patch: { vignette: 'noir', overlayOpacity: 0.72, duotoneWash: 'primary', duotoneOpacity: 0.22 } },
      { suffix: 'Clean Retail', suffixTr: 'Temiz Retail', patch: { fontPersonality: 'sans_modern', heroWeight: 800, heroUppercase: true } },
      { suffix: 'Warm Editorial', suffixTr: 'Sıcak Editoryal', patch: { duotoneWash: 'warm', duotoneOpacity: 0.2 } },
      { suffix: 'Social Proof', suffixTr: 'Sosyal Kanıt', patch: { showCtaPill: false, accentLine: 'both', heroScale: 0.9 } },
      { suffix: 'Luxury Frame', suffixTr: 'Lüks Çerçeve', patch: { frame: 'inset', fontPersonality: 'luxury_serif', heroWeight: 600 } },
    ],
  },
];

function mergeSpec(...layers: Partial<RemotionLayoutSpec>[]): RemotionLayoutSpec {
  return { ...BASE_SPEC, ...Object.assign({}, ...layers) } as RemotionLayoutSpec;
}

function buildTemplate(family: FamilyMeta, variantIndex: number, variant: FamilyMeta['variants'][0]): RemotionTemplateDefinition {
  const vibeCollection = family.collection;
  const agencyUpgrade = getAgencyStoryFamilyUpgrade(family.family);
  const merged = mergeSpec(
    { family: family.family, collection: 'Agency' },
    family.base,
    agencyUpgrade ?? {},
    variant.patch,
  );
  const spec = normalizeAgencyStorySpec(family.family, merged, vibeCollection);
  const nn = String(variantIndex + 1).padStart(2, '0');
  const id = `remotion_${family.family}_${nn}`;
  const variantTag = variant.suffix.toLowerCase().replace(/\s+/g, '_');

  return {
    id,
    family: family.family,
    collection: 'Agency',
    variantIndex,
    nameTr: `${family.nameTr} · ${variant.suffixTr}`,
    nameEn: `${family.nameEn} · ${variant.suffix}`,
    descTr: family.descTr,
    tags: agencyStoryTags(family.family, vibeCollection, [...family.tags, variantTag]),
    bestFor: family.bestFor,
    legacyComposition: family.legacyComposition,
    spec,
    sectors: family.sectors,
    status: 'active',
  };
}

export const REMOTION_TEMPLATE_CATALOG: RemotionTemplateDefinition[] = FAMILY_CATALOG.flatMap((family) =>
  family.variants.map((variant, i) => buildTemplate(family, i, variant)),
);

export const REMOTION_TEMPLATE_BY_ID = new Map(REMOTION_TEMPLATE_CATALOG.map((t) => [t.id, t]));

export const REMOTION_TEMPLATE_COUNT = REMOTION_TEMPLATE_CATALOG.length;

export function getRemotionTemplate(templateId: string): RemotionTemplateDefinition | undefined {
  return REMOTION_TEMPLATE_BY_ID.get(templateId);
}

export function listTemplatesByFamily(family: RemotionLayoutFamily): RemotionTemplateDefinition[] {
  return REMOTION_TEMPLATE_CATALOG.filter((t) => t.family === family);
}

export function listTemplatesByCollection(collection: RemotionLayoutSpec['collection']): RemotionTemplateDefinition[] {
  return REMOTION_TEMPLATE_CATALOG.filter((t) => t.collection === collection);
}

export function listTemplatesForIntent(intent: string): RemotionTemplateDefinition[] {
  return REMOTION_TEMPLATE_CATALOG.filter((t) => t.bestFor.includes(intent as TemplateIntent));
}

export const REMOTION_FAMILY_META = FAMILY_CATALOG.map(({ family, nameTr, nameEn, collection, descTr, tags, bestFor, variants }) => ({
  family,
  nameTr,
  nameEn,
  collection,
  descTr,
  tags,
  bestFor,
  variantCount: variants.length,
}));

/** Legacy composition → default catalog template */
export const LEGACY_COMPOSITION_TEMPLATE: Partial<Record<string, string>> = {
  EditorialStory: 'remotion_editorial_bottom_01',
  LuxurySplitStory: 'remotion_split_panel_01',
  CinematicStory: 'remotion_cinematic_center_01',
  CampaignHeroStory: 'remotion_campaign_hero_01',
  MagazineCoverStory: 'remotion_magazine_cover_01',
  GallerySeriesStory: 'remotion_gallery_series_01',
  EventAnnouncementStory: 'remotion_event_ticket_01',
};
